global using Reqnroll;
//global using Reqnroll.VisualStudio.Discovery.TagExpressions;
global using Reqnroll.IdeSupport.LSP.Connector.Models;
global using Reqnroll.IdeSupport.Common.Diagnostics;
global using Reqnroll.IdeSupport.Common.Configuration;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Text.RegularExpressions;
global using Gherkin;
global using Location = Gherkin.Ast.Location;
