// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Reqnroll.VisualStudio.Specs.Features.Editor
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "gherkin6")]
    public partial class KeywordCompletionFeature : object, Xunit.IClassFixture<KeywordCompletionFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "gherkin6"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "KeywordCompletion.feature"
#line hidden
        
        public KeywordCompletionFeature(KeywordCompletionFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Editor", "Keyword completion", @"Rules:

* Completion offers the keywords available at the cursor position
  * In the beginning of the file it offers Language, Tag and Feature
  * After a sceanrio it offers Step keywords, Scenario and Scenario Oultine
* Completion offers language-specific keywords
  * Offers the keywords of the configured language
  * Offers the keywords of the file language
* Completion offers step arguments
  * After a step offers data table and doc string markers
* Completion list is shown when the first letter is typed in a line
  * Completion list is shown when the first letter is typed in a line", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="In the beginning of the file it offers Language, Tag and Feature")]
        [Xunit.TraitAttribute("FeatureTitle", "Keyword completion")]
        [Xunit.TraitAttribute("Description", "In the beginning of the file it offers Language, Tag and Feature")]
        public async System.Threading.Tasks.Task InTheBeginningOfTheFileItOffersLanguageTagAndFeature()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("In the beginning of the file it offers Language, Tag and Feature", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
 await testRunner.AndAsync("the following feature file in the editor", "{caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
 await testRunner.WhenAsync("I invoke the \"Complete\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "item"});
                table26.AddRow(new string[] {
                            "#language:"});
                table26.AddRow(new string[] {
                            "@tag1"});
                table26.AddRow(new string[] {
                            "Feature:"});
                table26.AddRow(new string[] {
                            "Business Need:"});
                table26.AddRow(new string[] {
                            "Ability:"});
#line 24
 await testRunner.ThenAsync("a completion list should pop up with the following items", ((string)(null)), table26, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="After a sceanrio it offers Step keywords, Scenario, Scenario Oultine and Examples" +
            "")]
        [Xunit.TraitAttribute("FeatureTitle", "Keyword completion")]
        [Xunit.TraitAttribute("Description", "After a sceanrio it offers Step keywords, Scenario, Scenario Oultine and Examples" +
            "")]
        public async System.Threading.Tasks.Task AfterASceanrioItOffersStepKeywordsScenarioScenarioOultineAndExamples()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("After a sceanrio it offers Step keywords, Scenario, Scenario Oultine and Examples" +
                    "", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 33
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 34
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n  Given I have entered 50 into the " +
                        "calculator\r\n{caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
 await testRunner.WhenAsync("I invoke the \"Complete\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "item"});
                table27.AddRow(new string[] {
                            "Given"});
                table27.AddRow(new string[] {
                            "When"});
                table27.AddRow(new string[] {
                            "Then"});
                table27.AddRow(new string[] {
                            "And"});
                table27.AddRow(new string[] {
                            "But"});
                table27.AddRow(new string[] {
                            "Scenario:"});
                table27.AddRow(new string[] {
                            "Example:"});
                table27.AddRow(new string[] {
                            "Scenario Outline:"});
                table27.AddRow(new string[] {
                            "Scenario Template:"});
                table27.AddRow(new string[] {
                            "Examples:"});
                table27.AddRow(new string[] {
                            "Scenarios:"});
                table27.AddRow(new string[] {
                            "Rule:"});
#line 42
 await testRunner.ThenAsync("a completion list should pop up with the following keyword items", ((string)(null)), table27, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Completes keyword at the caret position")]
        [Xunit.TraitAttribute("FeatureTitle", "Keyword completion")]
        [Xunit.TraitAttribute("Description", "Completes keyword at the caret position")]
        public async System.Threading.Tasks.Task CompletesKeywordAtTheCaretPosition()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Completes keyword at the caret position", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 58
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 59
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n  Given I have entered 50 into the " +
                        "calculator\r\n  A{caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
 await testRunner.WhenAsync("I invoke the \"Complete\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
 await testRunner.AndAsync("commit the \"And\" completion item", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
 await testRunner.ThenAsync("the editor should be updated to", "Feature: Addition\r\nScenario: Add two numbers\r\n  Given I have entered 50 into the " +
                        "calculator\r\n  And ", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Replaces keyword at the caret position")]
        [Xunit.TraitAttribute("FeatureTitle", "Keyword completion")]
        [Xunit.TraitAttribute("Description", "Replaces keyword at the caret position")]
        public async System.Threading.Tasks.Task ReplacesKeywordAtTheCaretPosition()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Replaces keyword at the caret position", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 76
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 77
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 78
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n  Given I have entered 50 into the " +
                        "calculator\r\n  Gi{caret}ven I have entered 70 into the calculator", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
 await testRunner.WhenAsync("I invoke the \"Complete\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 86
 await testRunner.AndAsync("commit the \"And\" completion item", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 87
 await testRunner.ThenAsync("the editor should be updated to", "Feature: Addition\r\nScenario: Add two numbers\r\n  Given I have entered 50 into the " +
                        "calculator\r\n  And I have entered 70 into the calculator", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Offers the keywords of the configured language")]
        [Xunit.TraitAttribute("FeatureTitle", "Keyword completion")]
        [Xunit.TraitAttribute("Description", "Offers the keywords of the configured language")]
        public async System.Threading.Tasks.Task OffersTheKeywordsOfTheConfiguredLanguage()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Offers the keywords of the configured language", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 95
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 96
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 97
 await testRunner.AndAsync("the reqnroll.json configuration file contains", "{ \r\n\t\"language\": {\r\n\t\t\"feature\": \"hu-HU\"\r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 105
 await testRunner.AndAsync("the following feature file in the editor", "{caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
 await testRunner.WhenAsync("I invoke the \"Complete\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                            "item"});
                table28.AddRow(new string[] {
                            "Jellemző:"});
#line 110
 await testRunner.ThenAsync("a completion list should pop up with the following keyword items", ((string)(null)), table28, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Offers the keywords of the file language")]
        [Xunit.TraitAttribute("FeatureTitle", "Keyword completion")]
        [Xunit.TraitAttribute("Description", "Offers the keywords of the file language")]
        public async System.Threading.Tasks.Task OffersTheKeywordsOfTheFileLanguage()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Offers the keywords of the file language", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 114
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 115
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 116
 await testRunner.AndAsync("the following feature file in the editor", "#language: hu\r\n{caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 121
 await testRunner.WhenAsync("I invoke the \"Complete\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table29 = new global::Reqnroll.Table(new string[] {
                            "item"});
                table29.AddRow(new string[] {
                            "Jellemző:"});
#line 122
 await testRunner.ThenAsync("a completion list should pop up with the following keyword items", ((string)(null)), table29, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="After a step offers data table and doc string markers")]
        [Xunit.TraitAttribute("FeatureTitle", "Keyword completion")]
        [Xunit.TraitAttribute("Description", "After a step offers data table and doc string markers")]
        public async System.Threading.Tasks.Task AfterAStepOffersDataTableAndDocStringMarkers()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("After a step offers data table and doc string markers", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 126
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 127
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 128
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n  Given I have entered 50 into the " +
                        "calculator\r\n{caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 135
 await testRunner.WhenAsync("I invoke the \"Complete\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table30 = new global::Reqnroll.Table(new string[] {
                            "item"});
                table30.AddRow(new string[] {
                            "|"});
                table30.AddRow(new string[] {
                            "\"\"\""});
                table30.AddRow(new string[] {
                            "```"});
                table30.AddRow(new string[] {
                            "*"});
#line 136
 await testRunner.ThenAsync("a completion list should pop up with the following markers", ((string)(null)), table30, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Completion list is shown when the first letter is typed in a line")]
        [Xunit.TraitAttribute("FeatureTitle", "Keyword completion")]
        [Xunit.TraitAttribute("Description", "Completion list is shown when the first letter is typed in a line")]
        public async System.Threading.Tasks.Task CompletionListIsShownWhenTheFirstLetterIsTypedInALine()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Completion list is shown when the first letter is typed in a line", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 143
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 144
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 145
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\n  {caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 150
 await testRunner.WhenAsync("I invoke the \"Complete\" command by typing \"B\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table31 = new global::Reqnroll.Table(new string[] {
                            "item"});
                table31.AddRow(new string[] {
                            "Background:"});
                table31.AddRow(new string[] {
                            "Scenario:"});
                table31.AddRow(new string[] {
                            "Example:"});
                table31.AddRow(new string[] {
                            "Scenario Outline:"});
                table31.AddRow(new string[] {
                            "Scenario Template:"});
                table31.AddRow(new string[] {
                            "Rule:"});
#line 151
 await testRunner.ThenAsync("a completion list should pop up with the following keyword items", ((string)(null)), table31, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A short description is shown for each keyword")]
        [Xunit.TraitAttribute("FeatureTitle", "Keyword completion")]
        [Xunit.TraitAttribute("Description", "A short description is shown for each keyword")]
        public async System.Threading.Tasks.Task AShortDescriptionIsShownForEachKeyword()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A short description is shown for each keyword", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 160
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 161
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 162
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n  {caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 168
 await testRunner.AndAsync("the \"Complete\" command is being invoked", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 169
 await testRunner.WhenAsync("I invoke the \"Filter Completion\" command by typing \"Giv\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table32 = new global::Reqnroll.Table(new string[] {
                            "item",
                            "description"});
                table32.AddRow(new string[] {
                            "Given",
                            "Describes the context for the behaviour"});
#line 170
 await testRunner.ThenAsync("a completion list should pop up with the following keyword items", ((string)(null)), table32, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await KeywordCompletionFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await KeywordCompletionFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
