// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Reqnroll.VisualStudio.Specs.Features.Editor
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "doc:Traceability")]
    public partial class ScenarioTraceabilityFeature : object, Xunit.IClassFixture<ScenarioTraceabilityFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "doc:Traceability"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ScenarioTraceability.feature"
#line hidden
        
        public ScenarioTraceabilityFeature(ScenarioTraceabilityFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Editor", "Scenario traceability", @"Allow opening artifacts related to scenarios in browser, based on configured 
tags that match to a specific pattern.

E.g: tag @issue:1234 can be linked to a GitHub issue, like https://github.com/specsolutions/my-project/issues/1234.
For this, the tag pattern (Regex) has to be defined as 
	issue\:(?<id>\d+)
and the URL template as
	https://github.com/specsolutions/my-project/issues/{id}", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Turns configured tag to a link")]
        [Xunit.TraitAttribute("FeatureTitle", "Scenario traceability")]
        [Xunit.TraitAttribute("Description", "Turns configured tag to a link")]
        public async System.Threading.Tasks.Task TurnsConfiguredTagToALink()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Turns configured tag to a link", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 15
 await testRunner.AndAsync("the reqnroll.json configuration file contains", "{ \r\n\t\"ide\": {\r\n\t\t\"traceability\": {\r\n\t\t\t\"tagLinks\": [\r\n\t\t\t\t{\r\n\t\t\t\t\t\"tagPattern\": \"" +
                        "issue\\\\:(?<id>\\\\d+)\",\r\n\t\t\t\t\t\"urlTemplate\": \"https://github.com/specsolutions/my-" +
                        "project/issues/{id}\"\r\n\t\t\t\t}\r\n\t\t\t]\r\n\t\t}\r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\n\r\n@issue:1234\r\nScenario: Add two numbers\r\n\tWhen I press add", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
 await testRunner.ThenAsync("all Tag section should be highlighted as", "Feature: Addition\r\n\r\n{Tag}@issue:1234{/Tag}\r\nScenario: Add two numbers\r\n\tWhen I p" +
                        "ress add", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table33 = new global::Reqnroll.Table(new string[] {
                            "tag",
                            "url"});
                table33.AddRow(new string[] {
                            "@issue:1234",
                            "https://github.com/specsolutions/my-project/issues/1234"});
#line 46
 await testRunner.AndAsync("the tag links should target to the following URLs", ((string)(null)), table33, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Turns SpecSync tags to links automatically")]
        [Xunit.TraitAttribute("FeatureTitle", "Scenario traceability")]
        [Xunit.TraitAttribute("Description", "Turns SpecSync tags to links automatically")]
        public async System.Threading.Tasks.Task TurnsSpecSyncTagsToLinksAutomatically()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Turns SpecSync tags to links automatically", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 50
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 51
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 52
 await testRunner.AndAsync("the project is configured for SpecSync with Azure DevOps project URL \"https://dev" +
                        ".azure.com/specsolutions/deveroom-visualstudio\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\n\r\n@tc:1234\r\nScenario: Add two numbers\r\n\tWhen I press add", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table34 = new global::Reqnroll.Table(new string[] {
                            "tag",
                            "url"});
                table34.AddRow(new string[] {
                            "@tc:1234",
                            "https://dev.azure.com/specsolutions/deveroom-visualstudio/_workitems/edit/1234"});
#line 61
 await testRunner.ThenAsync("the tag links should target to the following URLs", ((string)(null)), table34, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ScenarioTraceabilityFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ScenarioTraceabilityFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
