// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Reqnroll.VisualStudio.Specs.Features.Editor
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class StepCompletionFeature : object, Xunit.IClassFixture<StepCompletionFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "StepCompletion.feature"
#line hidden
        
        public StepCompletionFeature(StepCompletionFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Editor", "Step Completion", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Offers step definitions of the scenario block at the caret")]
        [Xunit.TraitAttribute("FeatureTitle", "Step Completion")]
        [Xunit.TraitAttribute("Description", "Offers step definitions of the scenario block at the caret")]
        public async System.Threading.Tasks.Task OffersStepDefinitionsOfTheScenarioBlockAtTheCaret()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Offers step definitions of the scenario block at the caret", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
 await testRunner.GivenAsync("there is a Reqnroll project scope with calculator step definitions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n  Given I have entered 50 into the " +
                        "calculator\r\n  When {caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
 await testRunner.WhenAsync("I invoke the \"Complete\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table44 = new global::Reqnroll.Table(new string[] {
                            "item"});
                table44.AddRow(new string[] {
                            "I press add"});
#line 14
 await testRunner.ThenAsync("a completion list should pop up with the following items", ((string)(null)), table44, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Offers step definitions when space pressed after a step keyword")]
        [Xunit.TraitAttribute("FeatureTitle", "Step Completion")]
        [Xunit.TraitAttribute("Description", "Offers step definitions when space pressed after a step keyword")]
        public async System.Threading.Tasks.Task OffersStepDefinitionsWhenSpacePressedAfterAStepKeyword()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Offers step definitions when space pressed after a step keyword", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
 await testRunner.GivenAsync("there is a Reqnroll project scope with calculator step definitions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n  Given I have entered 50 into the " +
                        "calculator\r\n  When{caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
 await testRunner.WhenAsync("I invoke the \"Complete\" command by typing \" \"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table45 = new global::Reqnroll.Table(new string[] {
                            "item"});
                table45.AddRow(new string[] {
                            "I press add"});
#line 29
 await testRunner.ThenAsync("a completion list should pop up with the following items", ((string)(null)), table45, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Completes step at the caret position")]
        [Xunit.TraitAttribute("FeatureTitle", "Step Completion")]
        [Xunit.TraitAttribute("Description", "Completes step at the caret position")]
        public async System.Threading.Tasks.Task CompletesStepAtTheCaretPosition()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Completes step at the caret position", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
 await testRunner.GivenAsync("there is a Reqnroll project scope with calculator step definitions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n  When I {caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
 await testRunner.WhenAsync("I invoke the \"Complete\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
 await testRunner.AndAsync("commit the \"I press add\" completion item", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
 await testRunner.ThenAsync("the editor should be updated to", "Feature: Addition\r\nScenario: Add two numbers\r\n  When I press add", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Replaces step at the caret position")]
        [Xunit.TraitAttribute("FeatureTitle", "Step Completion")]
        [Xunit.TraitAttribute("Description", "Replaces step at the caret position")]
        public async System.Threading.Tasks.Task ReplacesStepAtTheCaretPosition()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Replaces step at the caret position", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 51
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 52
 await testRunner.GivenAsync("there is a Reqnroll project scope with calculator step definitions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 53
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n  When I {caret} press mulitply", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
 await testRunner.WhenAsync("I invoke the \"Complete\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
 await testRunner.AndAsync("commit the \"I press add\" completion item", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
 await testRunner.ThenAsync("the editor should be updated to", "Feature: Addition\r\nScenario: Add two numbers\r\n  When I press add", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Offers simple step definitions with parameter placeholders")]
        [Xunit.TraitAttribute("FeatureTitle", "Step Completion")]
        [Xunit.TraitAttribute("Description", "Offers simple step definitions with parameter placeholders")]
        public async System.Threading.Tasks.Task OffersSimpleStepDefinitionsWithParameterPlaceholders()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Offers simple step definitions with parameter placeholders", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 69
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 70
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table46 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "regex",
                            "param types"});
                table46.AddRow(new string[] {
                            "Given",
                            "^I have entered (.*) into the \"([^\"]*)\" calculator$",
                            "i|s"});
#line 71
 await testRunner.AndAsync("the following step definitions in the project:", ((string)(null)), table46, "And ");
#line hidden
#line 74
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n  Given {caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
 await testRunner.WhenAsync("I invoke the \"Complete\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table47 = new global::Reqnroll.Table(new string[] {
                            "item"});
                table47.AddRow(new string[] {
                            "I have entered [int] into the \"[string]\" calculator"});
#line 82
 await testRunner.ThenAsync("a completion list should pop up with the following items", ((string)(null)), table47, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Offers complex step definitions as regex")]
        [Xunit.TraitAttribute("FeatureTitle", "Step Completion")]
        [Xunit.TraitAttribute("Description", "Offers complex step definitions as regex")]
        public async System.Threading.Tasks.Task OffersComplexStepDefinitionsAsRegex()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Offers complex step definitions as regex", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 86
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 87
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table48 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "regex",
                            "param types"});
                table48.AddRow(new string[] {
                            "Given",
                            "^I use a (?:[step]+) with (\\d+) parameter$",
                            "i"});
#line 88
 await testRunner.AndAsync("the following step definitions in the project:", ((string)(null)), table48, "And ");
#line hidden
#line 91
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n  Given {caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
 await testRunner.WhenAsync("I invoke the \"Complete\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table49 = new global::Reqnroll.Table(new string[] {
                            "item"});
                table49.AddRow(new string[] {
                            "I use a (?:[step]+) with (\\d+) parameter"});
#line 99
 await testRunner.ThenAsync("a completion list should pop up with the following items", ((string)(null)), table49, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Filters completion list")]
        [Xunit.TraitAttribute("FeatureTitle", "Step Completion")]
        [Xunit.TraitAttribute("Description", "Filters completion list")]
        [Xunit.InlineDataAttribute("prefix match", "there is", "there is a calculator", new string[0])]
        [Xunit.InlineDataAttribute("contains", "calc", "there is a calculator", new string[0])]
        [Xunit.InlineDataAttribute("multiple word contains", "is a calc", "there is a calculator", new string[0])]
        [Xunit.InlineDataAttribute("multiple word any order", "calculator there", "there is a calculator", new string[0])]
        [Xunit.InlineDataAttribute("multiple word any order, prefix", "calculator the", "there is a calculator", new string[0])]
        [Xunit.InlineDataAttribute("multiple word any order, infix", "cul he", "there is a calculator", new string[0])]
        public async System.Threading.Tasks.Task FiltersCompletionList(string description, string filterText, string matchingItem, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("description", description);
            argumentsOfScenario.Add("filter text", filterText);
            argumentsOfScenario.Add("matching item", matchingItem);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filters completion list", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 103
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 104
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table50 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "regex"});
                table50.AddRow(new string[] {
                            "Given",
                            "^there is a calculator$"});
                table50.AddRow(new string[] {
                            "Given",
                            "^something else$"});
#line 105
 await testRunner.AndAsync("the following step definitions in the project:", ((string)(null)), table50, "And ");
#line hidden
#line 109
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n  Given {caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 115
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 116
 await testRunner.AndAsync("the \"Complete\" command has been invoked", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 117
 await testRunner.WhenAsync(string.Format("I invoke the \"Filter Completion\" command by typing \"{0}\"", filterText), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table51 = new global::Reqnroll.Table(new string[] {
                            "item"});
                table51.AddRow(new string[] {
                            string.Format("{0}", matchingItem)});
#line 118
 await testRunner.ThenAsync("a completion list should list the following items", ((string)(null)), table51, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await StepCompletionFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await StepCompletionFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
