// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Reqnroll.VisualStudio.Specs.Features.Editor
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class StepAnalysisFeature : object, Xunit.IClassFixture<StepAnalysisFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "StepAnalysis.feature"
#line hidden
        
        public StepAnalysisFeature(StepAnalysisFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Editor", "Step analysis", "Rules:\r\n\r\n* Highlight defined/undefined steps\r\n\t* Highlights defined/undefined st" +
                    "eps\r\n\t* Highlights step parameters\r\n\t* Analyses all examples of scenario outline" +
                    "\r\n* Show step definition errors\r\n\t* The step definition has invalid parameter co" +
                    "unt\r\n\t* Ambiguous step definitions\r\n* Handle scopes\r\n\t* Matches scoped step defi" +
                    "nitions\r\n\t* Analyses all scopes of background steps\r\n* Refresh analysis after bu" +
                    "ild\r\n\t* Step is just defined and the project is built\r\n\r\nResult Variations:\r\n* M" +
                    "atch\r\n\t* Matching step => jump\r\n\t\t* Unscoped\r\n        * DataTable&DocString => s" +
                    "elect overload based on param type\r\n\t\t* Scoped\r\n\t\t* Unscoped&Scoped => use scope" +
                    "d or unscoped depending on contex (no ambiguity)\r\n        * SO, but mathces to t" +
                    "he same stepdef\r\n\t* Binding errors (e.g. parameter count) => err,jump\r\n\t* OUT: P" +
                    "arameter error (e.g. invalid conversion)\r\n\t* OUT: Same method matches multiple w" +
                    "ays\r\n* Undefined\r\n\t* No candidating step definitions => undef\r\n\t* OUT: Some matc" +
                    "h, but with different type => error (now: undef)\r\n\t* OUT: Some match, but with d" +
                    "ifferent scope => error (now: undef)\r\n    * SO, but all (incl. empty) undefined " +
                    "=> undef\r\n* Ambiguous\r\n\t* Multiple matching step => err,list\r\n\t* Multiple step, " +
                    "some with binding/parameter errors => err,list\r\n    * SO, but all ambiguous => e" +
                    "rr,list (of merged candidates)\r\n* Multi-match (SO, Background)\r\n\t* All match => " +
                    "list\r\n\t* Some with binding/parameter errors => err,list\r\n\t* Some undefined => un" +
                    "def,list incl. generate step def\r\n\t* Some ambiguous => err,list", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Highlights defined/undefined steps")]
        [Xunit.TraitAttribute("FeatureTitle", "Step analysis")]
        [Xunit.TraitAttribute("Description", "Highlights defined/undefined steps")]
        public async System.Threading.Tasks.Task HighlightsDefinedUndefinedSteps()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Highlights defined/undefined steps", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 45
 await testRunner.GivenAsync("there is a Reqnroll project scope with calculator step definitions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 46
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I press add\r\n\tThen there is" +
                        " an undefined step", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 54
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
 await testRunner.ThenAsync("all section of types DefinedStep,UndefinedStep should be highlighted as", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen {DefinedStep}I press add{/D" +
                        "efinedStep}\r\n\tThen {UndefinedStep}there is an undefined step{/UndefinedStep}", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Highlights step parameters")]
        [Xunit.TraitAttribute("FeatureTitle", "Step analysis")]
        [Xunit.TraitAttribute("Description", "Highlights step parameters")]
        public async System.Threading.Tasks.Task HighlightsStepParameters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Highlights step parameters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 64
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 65
 await testRunner.GivenAsync("there is a Reqnroll project scope with calculator step definitions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 66
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I press add\r\n\tThen the resu" +
                        "lt should be 120 on the screen", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 74
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
 await testRunner.ThenAsync("all StepParameter section should be highlighted as", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I press add\r\n\tThen the resu" +
                        "lt should be {StepParameter}120{/StepParameter} on the screen", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Analyses all examples of scenario outline")]
        [Xunit.TraitAttribute("FeatureTitle", "Step analysis")]
        [Xunit.TraitAttribute("Description", "Analyses all examples of scenario outline")]
        public async System.Threading.Tasks.Task AnalysesAllExamplesOfScenarioOutline()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Analyses all examples of scenario outline", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 84
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 85
 await testRunner.GivenAsync("there is a Reqnroll project scope with calculator step definitions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 86
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\n\r\nScenario Outline: Add two numbers\r\n\t# this step is both defi" +
                        "ned (1st ex) and undefined (2nd ex)\r\n\tWhen I press <what>\r\nExamples: \r\n\t| what  " +
                        "       |\r\n\t| add          |\r\n\t| undefined op |", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 98
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 99
 await testRunner.ThenAsync("all section of types DefinedStep,UndefinedStep should be highlighted as", @"Feature: Addition

Scenario Outline: Add two numbers
	# this step is both defined (1st ex) and undefined (2nd ex)
	When {DefinedStep}{UndefinedStep}I press <what>{/UndefinedStep}{/DefinedStep}
Examples: 
	| what         |
	| add          |
	| undefined op |", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="The step definition has invalid parameter count")]
        [Xunit.TraitAttribute("FeatureTitle", "Step analysis")]
        [Xunit.TraitAttribute("Description", "The step definition has invalid parameter count")]
        public async System.Threading.Tasks.Task TheStepDefinitionHasInvalidParameterCount()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The step definition has invalid parameter count", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 112
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 113
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table35 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "regex",
                            "param types"});
                table35.AddRow(new string[] {
                            "When",
                            "I use a step with (\\d+) parameter",
                            ""});
#line 114
 await testRunner.AndAsync("the following step definitions in the project:", ((string)(null)), table35, "And ");
#line hidden
#line 117
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\n\r\nScenario: My scenario\r\n\tWhen I use a step with 1 parameter", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 124
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
 await testRunner.ThenAsync("all BindingError section should be highlighted as", "Feature: Addition\r\n\r\nScenario: My scenario\r\n\tWhen {BindingError}I use a step with" +
                        " 1 parameter{/BindingError}", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ambiguous step definitions")]
        [Xunit.TraitAttribute("FeatureTitle", "Step analysis")]
        [Xunit.TraitAttribute("Description", "Ambiguous step definitions")]
        public async System.Threading.Tasks.Task AmbiguousStepDefinitions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ambiguous step definitions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 133
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 134
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table36 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "regex",
                            "method"});
                table36.AddRow(new string[] {
                            "When",
                            "I use a .*",
                            "M1"});
                table36.AddRow(new string[] {
                            "When",
                            "I .* a step",
                            "M2"});
#line 135
 await testRunner.AndAsync("the following step definitions in the project:", ((string)(null)), table36, "And ");
#line hidden
#line 139
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\n\r\nScenario: My scenario\r\n\tWhen I use a step", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 146
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 147
 await testRunner.ThenAsync("all BindingError section should be highlighted as", "Feature: Addition\r\n\r\nScenario: My scenario\r\n\tWhen {BindingError}I use a step{/Bin" +
                        "dingError}", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Matches tag scoped step definitions")]
        [Xunit.TraitAttribute("FeatureTitle", "Step analysis")]
        [Xunit.TraitAttribute("Description", "Matches tag scoped step definitions")]
        public async System.Threading.Tasks.Task MatchesTagScopedStepDefinitions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Matches tag scoped step definitions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 155
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 156
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table37 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "regex",
                            "tag scope"});
                table37.AddRow(new string[] {
                            "When",
                            "I use mytag scoped step",
                            "@mytag"});
                table37.AddRow(new string[] {
                            "When",
                            "I use featuretag scoped step",
                            "@featuretag"});
#line 157
 await testRunner.AndAsync("the following step definitions in the project:", ((string)(null)), table37, "And ");
#line hidden
#line 161
 await testRunner.WhenAsync("the following feature file is opened in the editor", "@featuretag\r\nFeature: Addition\r\n\r\n@mytag\r\nScenario: Tagged scenario\r\n\tWhen I use " +
                        "mytag scoped step\r\n\tWhen I use featuretag scoped step\r\n\r\nScenario: Untagged scen" +
                        "ario\r\n\tWhen I use mytag scoped step\r\n\tWhen I use featuretag scoped step", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 175
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 176
 await testRunner.ThenAsync("all section of types DefinedStep,UndefinedStep should be highlighted as", @"@featuretag
Feature: Addition

@mytag
Scenario: Tagged scenario
	When {DefinedStep}I use mytag scoped step{/DefinedStep}
	When {DefinedStep}I use featuretag scoped step{/DefinedStep}

Scenario: Untagged scenario
	When {UndefinedStep}I use mytag scoped step{/UndefinedStep}
	When {DefinedStep}I use featuretag scoped step{/DefinedStep}", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Matches feature scoped step definitions")]
        [Xunit.TraitAttribute("FeatureTitle", "Step analysis")]
        [Xunit.TraitAttribute("Description", "Matches feature scoped step definitions")]
        public async System.Threading.Tasks.Task MatchesFeatureScopedStepDefinitions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Matches feature scoped step definitions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 191
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 192
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table38 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "regex",
                            "feature scope"});
                table38.AddRow(new string[] {
                            "When",
                            "I use a feature scoped step",
                            "Addition"});
                table38.AddRow(new string[] {
                            "When",
                            "I use a feature scoped step",
                            "Substraction"});
#line 193
 await testRunner.AndAsync("the following step definitions in the project:", ((string)(null)), table38, "And ");
#line hidden
#line 197
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\n\r\nScenario: Random scenario\r\n\tWhen I use a feature scoped step" +
                        "", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 204
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 205
 await testRunner.ThenAsync("all section of types DefinedStep should be highlighted as", "Feature: Addition\r\n\r\nScenario: Random scenario\r\n\tWhen {DefinedStep}I use a featur" +
                        "e scoped step{/DefinedStep}", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 212
 await testRunner.AndAsync("no binding error should be highlighted", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Matches scenario scoped step definitions")]
        [Xunit.TraitAttribute("FeatureTitle", "Step analysis")]
        [Xunit.TraitAttribute("Description", "Matches scenario scoped step definitions")]
        public async System.Threading.Tasks.Task MatchesScenarioScopedStepDefinitions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Matches scenario scoped step definitions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 214
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 215
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table39 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "regex",
                            "scenario scope"});
                table39.AddRow(new string[] {
                            "When",
                            "I use a scenario scoped step",
                            "Random scenario"});
                table39.AddRow(new string[] {
                            "When",
                            "I use a scenario scoped step",
                            ""});
#line 216
 await testRunner.AndAsync("the following step definitions in the project:", ((string)(null)), table39, "And ");
#line hidden
#line 220
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\n\r\nScenario: Random scenario\r\n\tWhen I use a scenario scoped ste" +
                        "p", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 227
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 228
 await testRunner.ThenAsync("all section of types DefinedStep should be highlighted as", "Feature: Addition\r\n\r\nScenario: Random scenario\r\n\tWhen {DefinedStep}I use a scenar" +
                        "io scoped step{/DefinedStep}", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 235
 await testRunner.AndAsync("no binding error should be highlighted", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Matches combination scoped step definitions")]
        [Xunit.TraitAttribute("FeatureTitle", "Step analysis")]
        [Xunit.TraitAttribute("Description", "Matches combination scoped step definitions")]
        public async System.Threading.Tasks.Task MatchesCombinationScopedStepDefinitions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Matches combination scoped step definitions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 237
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 238
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table40 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "regex",
                            "scenario scope",
                            "feature scope",
                            "tag scope"});
                table40.AddRow(new string[] {
                            "When",
                            "I use a combination scoped step",
                            "Random scenario",
                            "Addition",
                            "@mytag"});
                table40.AddRow(new string[] {
                            "When",
                            "I use a feature and tag scoped step",
                            "",
                            "Addition",
                            "@mytag"});
                table40.AddRow(new string[] {
                            "When",
                            "I use a feature scoped step",
                            "",
                            "Addition",
                            "@mytag"});
#line 239
 await testRunner.AndAsync("the following step definitions in the project:", ((string)(null)), table40, "And ");
#line hidden
#line 244
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\n\r\n@mytag\r\nScenario: Random scenario\r\n\tWhen I use a combination" +
                        " scoped step\r\n\r\n@mytag\r\nScenario: Another scenario\r\n\tWhen I use a feature and ta" +
                        "g scoped step\r\n\r\nScenario: Yet another scenario\r\n\tWhen I use a feature scoped st" +
                        "ep", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 259
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 260
 await testRunner.ThenAsync("all section of types DefinedStep,UndefinedStep should be highlighted as", @"Feature: Addition

@mytag
Scenario: Random scenario
	When {DefinedStep}I use a combination scoped step{/DefinedStep}

@mytag
Scenario: Another scenario
	When {DefinedStep}I use a feature and tag scoped step{/DefinedStep}

Scenario: Yet another scenario
	When {UndefinedStep}I use a feature scoped step{/UndefinedStep}", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 275
 await testRunner.AndAsync("no binding error should be highlighted", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Matches on multiple tags (without improperly highlighting as Ambiguous)")]
        [Xunit.TraitAttribute("FeatureTitle", "Step analysis")]
        [Xunit.TraitAttribute("Description", "Matches on multiple tags (without improperly highlighting as Ambiguous)")]
        public async System.Threading.Tasks.Task MatchesOnMultipleTagsWithoutImproperlyHighlightingAsAmbiguous()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Matches on multiple tags (without improperly highlighting as Ambiguous)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 277
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 278
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table41 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "regex",
                            "tag scope"});
                table41.AddRow(new string[] {
                            "When",
                            "I use a step with multiple tags",
                            "@mytag1,@mytag2"});
#line 279
 await testRunner.AndAsync("the following step definition with mulitple Tag Scopes in the project:", ((string)(null)), table41, "And ");
#line hidden
#line 282
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\n\r\n@mytag1\r\n@mytag2\r\nScenario: Random scenario\r\n\tWhen I use a s" +
                        "tep with multiple tags\r\n", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 292
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 293
 await testRunner.ThenAsync("all section of types DefinedStep should be highlighted as", "Feature: Addition\r\n\r\n@mytag1\r\n@mytag2\r\nScenario: Random scenario\r\n\tWhen {DefinedS" +
                        "tep}I use a step with multiple tags{/DefinedStep}", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 302
 await testRunner.AndAsync("no binding error should be highlighted", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Analyses all scopes of background steps")]
        [Xunit.TraitAttribute("FeatureTitle", "Step analysis")]
        [Xunit.TraitAttribute("Description", "Analyses all scopes of background steps")]
        public async System.Threading.Tasks.Task AnalysesAllScopesOfBackgroundSteps()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Analyses all scopes of background steps", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 304
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 305
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table42 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "regex",
                            "tag scope"});
                table42.AddRow(new string[] {
                            "Given",
                            "I use scenariotag scoped step",
                            "@scenariotag"});
                table42.AddRow(new string[] {
                            "Given",
                            "I use ruletag scoped step",
                            "@ruletag"});
                table42.AddRow(new string[] {
                            "Given",
                            "I use othertag scoped step",
                            "@othertag"});
                table42.AddRow(new string[] {
                            "When",
                            "I use a normal step",
                            ""});
#line 306
 await testRunner.AndAsync("the following step definitions in the project:", ((string)(null)), table42, "And ");
#line hidden
#line 312
 await testRunner.WhenAsync("the following feature file is opened in the editor", @"Feature: Addition

Background: 
	Given I use scenariotag scoped step
	Given I use othertag scoped step

@scenariotag
Scenario: Tagged scenario
	When I use a normal step

@ruletag
Rule: Sample rule

Background: 
	Given I use ruletag scoped step
	Given I use othertag scoped step

@scenariotag
Scenario: Scenario in tagged rule
	When I use a normal step", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 335
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 336
 await testRunner.ThenAsync("all section of types DefinedStep,UndefinedStep should be highlighted as", @"Feature: Addition

Background: 
	Given {DefinedStep}I use scenariotag scoped step{/DefinedStep}
	Given {UndefinedStep}I use othertag scoped step{/UndefinedStep}

@scenariotag
Scenario: Tagged scenario
	When {DefinedStep}I use a normal step{/DefinedStep}

@ruletag
Rule: Sample rule

Background: 
	Given {DefinedStep}I use ruletag scoped step{/DefinedStep}
	Given {UndefinedStep}I use othertag scoped step{/UndefinedStep}

@scenariotag
Scenario: Scenario in tagged rule
	When {DefinedStep}I use a normal step{/DefinedStep}", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Step is just defined and the project is built")]
        [Xunit.TraitAttribute("FeatureTitle", "Step analysis")]
        [Xunit.TraitAttribute("Description", "Step is just defined and the project is built")]
        public async System.Threading.Tasks.Task StepIsJustDefinedAndTheProjectIsBuilt()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Step is just defined and the project is built", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 361
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 362
 await testRunner.GivenAsync("there is a Reqnroll project scope with calculator step definitions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 363
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I press add\r\n\tThen there is" +
                        " an undefined step", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table43 = new global::Reqnroll.Table(new string[] {
                            "method",
                            "type",
                            "regex"});
                table43.AddRow(new string[] {
                            "ThenNewStep1",
                            "Then",
                            "there is an undefined step"});
#line 371
 await testRunner.WhenAsync("a new step definition is added to the project as:", ((string)(null)), table43, "When ");
#line hidden
#line 374
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 375
 await testRunner.ThenAsync("all section of types DefinedStep,UndefinedStep should be highlighted as", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen {DefinedStep}I press add{/D" +
                        "efinedStep}\r\n\tThen {DefinedStep}there is an undefined step{/DefinedStep}", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await StepAnalysisFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await StepAnalysisFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
