// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Reqnroll.VisualStudio.Specs.Features.Editor
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SyntaxColoringFeature : object, Xunit.IClassFixture<SyntaxColoringFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SyntaxColoring.feature"
#line hidden
        
        public SyntaxColoringFeature(SyntaxColoringFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Editor", "Syntax coloring", @"Rules:

* Highlight definition line keywords
	* Highlights definition line keywords
* Highlight tags
	* Highlights tags
* Highlight definition descriptions
	* Highlights definition descriptions
* Highlight step keywords
	* Highlights step keywords
	* Highlights non-English step keywords
	* TODO: Highlights non-English step keywords when language is defined in Reqnroll config
* Highlight comments
	* Highlights comments
* Highlight step arguments
	* Highlights doc strings
	* Highlights data tables
* Highlight Scenario Outline placeholders
	* Highlights Scenario Outline placeholders", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Highlights definition line keywords")]
        [Xunit.TraitAttribute("FeatureTitle", "Syntax coloring")]
        [Xunit.TraitAttribute("Description", "Highlights definition line keywords")]
        public async System.Threading.Tasks.Task HighlightsDefinitionLineKeywords()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Highlights definition line keywords", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\n\r\nBackground:\r\n\tGiven I have entered 50 into the calculator\r\n\r" +
                        "\nScenario: Add two numbers\r\n\tWhen I press add\r\n\r\nScenario Outline: Add two numbe" +
                        "rs outline\r\n\tWhen I press <op>\r\nExamples:\r\n\t| op  |\r\n\t| add |", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
 await testRunner.ThenAsync("all DefinitionLineKeyword section should be highlighted as", @"{DefinitionLineKeyword}Feature:{/DefinitionLineKeyword} Addition

{DefinitionLineKeyword}Background:{/DefinitionLineKeyword}
	Given I have entered 50 into the calculator

{DefinitionLineKeyword}Scenario:{/DefinitionLineKeyword} Add two numbers
	When I press add

{DefinitionLineKeyword}Scenario Outline:{/DefinitionLineKeyword} Add two numbers outline
	When I press <op>
{DefinitionLineKeyword}Examples:{/DefinitionLineKeyword}
	| op  |
	| add |", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Highlights rule line keywords")]
        [Xunit.TraitAttribute("FeatureTitle", "Syntax coloring")]
        [Xunit.TraitAttribute("Description", "Highlights rule line keywords")]
        [Xunit.TraitAttribute("Category", "gherkin6")]
        public async System.Threading.Tasks.Task HighlightsRuleLineKeywords()
        {
            string[] tagsOfScenario = new string[] {
                    "gherkin6"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Highlights rule line keywords", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 61
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
 await testRunner.WhenAsync("the following feature file is opened in the editor", @"Feature: Addition

Scenario: General feature scenario
	When I press add

Rule: Empty rule

Rule: This is a rule

Scenario: Scenario illustrating a rule
	When I press add

Rule: This is a rule with a background

Background:
	Given I have entered 50 into the calculator			

Scenario: Scenario illustrating a rule with a background
	When I press add", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
 await testRunner.ThenAsync("all DefinitionLineKeyword section should be highlighted as", @"{DefinitionLineKeyword}Feature:{/DefinitionLineKeyword} Addition

{DefinitionLineKeyword}Scenario:{/DefinitionLineKeyword} General feature scenario
	When I press add

{DefinitionLineKeyword}Rule:{/DefinitionLineKeyword} Empty rule

{DefinitionLineKeyword}Rule:{/DefinitionLineKeyword} This is a rule

{DefinitionLineKeyword}Scenario:{/DefinitionLineKeyword} Scenario illustrating a rule
	When I press add

{DefinitionLineKeyword}Rule:{/DefinitionLineKeyword} This is a rule with a background

{DefinitionLineKeyword}Background:{/DefinitionLineKeyword}
	Given I have entered 50 into the calculator			

{DefinitionLineKeyword}Scenario:{/DefinitionLineKeyword} Scenario illustrating a rule with a background
	When I press add", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Highlights tags")]
        [Xunit.TraitAttribute("FeatureTitle", "Syntax coloring")]
        [Xunit.TraitAttribute("Description", "Highlights tags")]
        public async System.Threading.Tasks.Task HighlightsTags()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Highlights tags", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 107
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 108
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 109
 await testRunner.WhenAsync("the following feature file is opened in the editor", "@foo @bar\r\n@baz\r\nFeature: Addition\r\n\r\n@qux\r\nScenario: Add two numbers\r\n\tWhen I pr" +
                        "ess add\r\n\r\n@rqux\r\nRule: Commutativity\r\n\r\n@quux\r\nScenario Outline: Add two number" +
                        "s outline\r\n\tWhen I press <op>\r\n@corge\r\nExamples:\r\n\t| op  |\r\n\t| add |", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 130
 await testRunner.ThenAsync("all Tag section should be highlighted as", @"{Tag}@foo{/Tag} {Tag}@bar{/Tag}
{Tag}@baz{/Tag}
Feature: Addition

{Tag}@qux{/Tag}
Scenario: Add two numbers
	When I press add

{Tag}@rqux{/Tag}
Rule: Commutativity

{Tag}@quux{/Tag}
Scenario Outline: Add two numbers outline
	When I press <op>
{Tag}@corge{/Tag}
Examples:
	| op  |
	| add |", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Highlights definition descriptions")]
        [Xunit.TraitAttribute("FeatureTitle", "Syntax coloring")]
        [Xunit.TraitAttribute("Description", "Highlights definition descriptions")]
        public async System.Threading.Tasks.Task HighlightsDefinitionDescriptions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Highlights definition descriptions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 152
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 153
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 154
 await testRunner.WhenAsync("the following feature file is opened in the editor", @"Feature: Addition

This is a description of a feature
	with indented line

	with empty line

Background:
	This is a description of a background
	Given I have entered 50 into the calculator

Scenario: Add two numbers
	This is a description of a scenario
	When I press add

Scenario Outline: Add two numbers outline
	This is a description of a outline
	When I press <op>
Examples:
	This is a description of an examples block
	| op  |
	| add |", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 179
 await testRunner.ThenAsync("all Description section should be highlighted as", @"Feature: Addition

{Description}This is a description of a feature
	with indented line

	with empty line{/Description}

Background:
{Description}	This is a description of a background{/Description}
	Given I have entered 50 into the calculator

Scenario: Add two numbers
{Description}	This is a description of a scenario{/Description}
	When I press add

Scenario Outline: Add two numbers outline
{Description}	This is a description of a outline{/Description}
	When I press <op>
Examples:
{Description}	This is a description of an examples block{/Description}
	| op  |
	| add |", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Highlights step keywords")]
        [Xunit.TraitAttribute("FeatureTitle", "Syntax coloring")]
        [Xunit.TraitAttribute("Description", "Highlights step keywords")]
        public async System.Threading.Tasks.Task HighlightsStepKeywords()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Highlights step keywords", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 206
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 207
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 208
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tGiven I have entered 50 into the" +
                        " calculator\r\n\tAnd I have entered 70 into the calculator\r\n\tWhen I press add\r\n\tThe" +
                        "n the result should be 120 on the screen\r\n\tBut there should be no error indicate" +
                        "d", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 219
 await testRunner.ThenAsync("all StepKeyword section should be highlighted as", @"Feature: Addition

Scenario: Add two numbers
	{StepKeyword}Given {/StepKeyword}I have entered 50 into the calculator
	{StepKeyword}And {/StepKeyword}I have entered 70 into the calculator
	{StepKeyword}When {/StepKeyword}I press add
	{StepKeyword}Then {/StepKeyword}the result should be 120 on the screen
	{StepKeyword}But {/StepKeyword}there should be no error indicated", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Highlights non-English step keywords")]
        [Xunit.TraitAttribute("FeatureTitle", "Syntax coloring")]
        [Xunit.TraitAttribute("Description", "Highlights non-English step keywords")]
        public async System.Threading.Tasks.Task HighlightsNon_EnglishStepKeywords()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Highlights non-English step keywords", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 231
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 232
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 233
 await testRunner.WhenAsync("the following feature file is opened in the editor", "#language: hu-HU\r\nJellemző: Összeadás\r\n\r\nForgatókönyv: Két számot összeadok\r\n\tAme" +
                        "nnyiben összadom a számokat", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 241
 await testRunner.ThenAsync("all section of types StepKeyword, DefinitionLineKeyword should be highlighted as", "#language: hu-HU\r\n{DefinitionLineKeyword}Jellemző:{/DefinitionLineKeyword} Összea" +
                        "dás\r\n\r\n{DefinitionLineKeyword}Forgatókönyv:{/DefinitionLineKeyword} Két számot ö" +
                        "sszeadok\r\n\t{StepKeyword}Amennyiben {/StepKeyword}összadom a számokat", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Highlights non-English step keywords using default feature language")]
        [Xunit.TraitAttribute("FeatureTitle", "Syntax coloring")]
        [Xunit.TraitAttribute("Description", "Highlights non-English step keywords using default feature language")]
        public async System.Threading.Tasks.Task HighlightsNon_EnglishStepKeywordsUsingDefaultFeatureLanguage()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Highlights non-English step keywords using default feature language", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 250
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 251
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 252
 await testRunner.AndAsync("the reqnroll.json configuration file contains", "{ \r\n\t\"language\": {\r\n\t\t\"feature\": \"hu-HU\"\r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 260
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Jellemző: Összeadás\r\n\r\nForgatókönyv: Két számot összeadok\r\n\tAmennyiben összadom a" +
                        " számokat", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 267
 await testRunner.ThenAsync("all section of types StepKeyword, DefinitionLineKeyword should be highlighted as", "{DefinitionLineKeyword}Jellemző:{/DefinitionLineKeyword} Összeadás\r\n\r\n{Definition" +
                        "LineKeyword}Forgatókönyv:{/DefinitionLineKeyword} Két számot összeadok\r\n\t{StepKe" +
                        "yword}Amennyiben {/StepKeyword}összadom a számokat", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Highlights comments")]
        [Xunit.TraitAttribute("FeatureTitle", "Syntax coloring")]
        [Xunit.TraitAttribute("Description", "Highlights comments")]
        public async System.Threading.Tasks.Task HighlightsComments()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Highlights comments", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 275
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 276
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 277
 await testRunner.WhenAsync("the following feature file is opened in the editor", "#language: en-US\r\nFeature: Addition\r\n\r\n# this is a comment\r\n\t# this is also a com" +
                        "ment", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 285
 await testRunner.ThenAsync("all Comment section should be highlighted as", "{Comment}#language: en-US{/Comment}\r\nFeature: Addition\r\n\r\n{Comment}# this is a co" +
                        "mment{/Comment}\r\n{Comment}\t# this is also a comment{/Comment}", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Highlights doc strings")]
        [Xunit.TraitAttribute("FeatureTitle", "Syntax coloring")]
        [Xunit.TraitAttribute("Description", "Highlights doc strings")]
        public async System.Threading.Tasks.Task HighlightsDocStrings()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Highlights doc strings", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 294
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 295
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 296
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n\tGiven the following formulas\r\n\t\t``" +
                        "`\r\n\t\t2 + 3\r\n\t\t\t4 * 8\r\n\r\n\t\t6 / 2\r\n\t\t```\r\n\tWhen I calculate the results", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 309
 await testRunner.ThenAsync("all DocString section should be highlighted as", "Feature: Addition\r\nScenario: Add two numbers\r\n\tGiven the following formulas\r\n{Doc" +
                        "String}\t\t```\r\n\t\t2 + 3\r\n\t\t\t4 * 8\r\n\r\n\t\t6 / 2\r\n\t\t```{/DocString}\r\n\tWhen I calculate" +
                        " the results", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Highlights data table")]
        [Xunit.TraitAttribute("FeatureTitle", "Syntax coloring")]
        [Xunit.TraitAttribute("Description", "Highlights data table")]
        public async System.Threading.Tasks.Task HighlightsDataTable()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Highlights data table", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 323
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 324
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 325
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n\tGiven the operands entered\r\n\t\t| op" +
                        "erand | type           |\r\n\t\t| 42      | integer        |\r\n\t\t| 7.1     | floating" +
                        " point |\r\n\tWhen I calculate the results", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 335
 await testRunner.ThenAsync("all section of types DataTable, DataTableHeader should be highlighted as", @"Feature: Addition
Scenario: Add two numbers
	Given the operands entered
{DataTable}		| {DataTableHeader}operand{/DataTableHeader} | {DataTableHeader}type{/DataTableHeader}           |
		| 42      | integer        |
		| 7.1     | floating point |{/DataTable}
	When I calculate the results", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Highlights Scenario Outline placeholders")]
        [Xunit.TraitAttribute("FeatureTitle", "Syntax coloring")]
        [Xunit.TraitAttribute("Description", "Highlights Scenario Outline placeholders")]
        public async System.Threading.Tasks.Task HighlightsScenarioOutlinePlaceholders()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Highlights Scenario Outline placeholders", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 346
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 347
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 348
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\nScenario Outline: Add two numbers\r\n\tGiven there is a number <a" +
                        "> and <b>\r\n\tWhen I press <op>\r\nExamples:\r\n\t| a | b | op  |\r\n\t| 1 | 2 | add |", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 358
 await testRunner.ThenAsync("all ScenarioOutlinePlaceholder section should be highlighted as", @"Feature: Addition
Scenario Outline: Add two numbers
	Given there is a number {ScenarioOutlinePlaceholder}<a>{/ScenarioOutlinePlaceholder} and {ScenarioOutlinePlaceholder}<b>{/ScenarioOutlinePlaceholder}
	When I press {ScenarioOutlinePlaceholder}<op>{/ScenarioOutlinePlaceholder}
Examples:
	| {ScenarioOutlinePlaceholder}a{/ScenarioOutlinePlaceholder} | {ScenarioOutlinePlaceholder}b{/ScenarioOutlinePlaceholder} | {ScenarioOutlinePlaceholder}op{/ScenarioOutlinePlaceholder}  |
	| 1 | 2 | add |", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Default feature file language was changed")]
        [Xunit.TraitAttribute("FeatureTitle", "Syntax coloring")]
        [Xunit.TraitAttribute("Description", "Default feature file language was changed")]
        [Xunit.TraitAttribute("Category", "quarantine")]
        public async System.Threading.Tasks.Task DefaultFeatureFileLanguageWasChanged()
        {
            string[] tagsOfScenario = new string[] {
                    "quarantine"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Default feature file language was changed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 373
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 374
 await testRunner.GivenAsync("there is a non-Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 375
 await testRunner.AndAsync("the reqnroll.json configuration file contains", "{ \r\n\t\"language\": {\r\n\t\t\"feature\": \"en-US\"\r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 383
 await testRunner.AndAsync("the following feature file in the editor", "Jellemző: Összeadás\r\n\r\nForgatókönyv: Két számot összeadok\r\n\tAmennyiben összadom a" +
                        " számokat", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 390
 await testRunner.WhenAsync("the reqnroll.json configuration file is updated to", "{ \r\n\t\"language\": {\r\n\t\t\"feature\": \"hu-HU\"\r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 398
 await testRunner.AndAsync("the project is built", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 399
 await testRunner.ThenAsync("all section of types StepKeyword, DefinitionLineKeyword should be highlighted as", "{DefinitionLineKeyword}Jellemző:{/DefinitionLineKeyword} Összeadás\r\n\r\n{Definition" +
                        "LineKeyword}Forgatókönyv:{/DefinitionLineKeyword} Két számot összeadok\r\n\t{StepKe" +
                        "yword}Amennyiben {/StepKeyword}összadom a számokat", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Do not highlight undefined step keywords")]
        [Xunit.TraitAttribute("FeatureTitle", "Syntax coloring")]
        [Xunit.TraitAttribute("Description", "Do not highlight undefined step keywords")]
        [Xunit.InlineDataAttribute("FeatureFileContainerProject", new string[0])]
        [Xunit.InlineDataAttribute("OtherProject", new string[0])]
        [Xunit.InlineDataAttribute("Uninitialized", new string[0])]
        public async System.Threading.Tasks.Task DoNotHighlightUndefinedStepKeywords(string projectKind, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("projectKind", projectKind);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Do not highlight undefined step keywords", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 407
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 408
 await testRunner.GivenAsync(string.Format("there is a project scope which is {0}", projectKind), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 409
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tGiven I have entered 50 into the" +
                        " calculator\r\n\tAnd I have entered 70 into the calculator\r\n\tWhen I press add\r\n\tThe" +
                        "n the result should be 120 on the screen\r\n\tBut there should be no error indicate" +
                        "d", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 420
 await testRunner.ThenAsync("there are no sections of type UndefinedStep", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await SyntaxColoringFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await SyntaxColoringFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
