// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Reqnroll.VisualStudio.Specs.Features.Editor.Commands
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AutomaticTableFormattingCommandFeature : object, Xunit.IClassFixture<AutomaticTableFormattingCommandFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AutoFormatTableCommand.feature"
#line hidden
        
        public AutomaticTableFormattingCommandFeature(AutomaticTableFormattingCommandFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Editor/Commands", "Automatic table formatting command", "Rules:\r\n\r\n* Autoformats DataTable\r\n\t* Autoformats DataTable when typing last pipe" +
                    "\r\n\t* Autoformats DataTable when typing middle pipe\r\n\t* Autoformats one-liner Dat" +
                    "aTable\r\n* Autoformats Examples table", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Autoformats DataTable when typing last pipe")]
        [Xunit.TraitAttribute("FeatureTitle", "Automatic table formatting command")]
        [Xunit.TraitAttribute("Description", "Autoformats DataTable when typing last pipe")]
        public async System.Threading.Tasks.Task AutoformatsDataTableWhenTypingLastPipe()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Autoformats DataTable when typing last pipe", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n\tGiven the following numbers added\r" +
                        "\n\t\t|  number| reason |\r\n\t\t  |   1   | first number  |\r\n\t   | 2  |second number {" +
                        "caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
 await testRunner.WhenAsync("I invoke the \"Auto Format Table\" command by typing \"|\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
 await testRunner.ThenAsync("the editor should be updated to", "Feature: Addition\r\nScenario: Add two numbers\r\n\tGiven the following numbers added\r" +
                        "\n\t\t| number | reason        |\r\n\t\t|      1 | first number  |\r\n\t\t|      2 | second" +
                        " number |", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Autoformats DataTable when typing middle pipe")]
        [Xunit.TraitAttribute("FeatureTitle", "Automatic table formatting command")]
        [Xunit.TraitAttribute("Description", "Autoformats DataTable when typing middle pipe")]
        public async System.Threading.Tasks.Task AutoformatsDataTableWhenTypingMiddlePipe()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Autoformats DataTable when typing middle pipe", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n\tGiven the following numbers added\r" +
                        "\n\t\t|  number| reason |\r\n\t\t  |   1   {caret} first number  |\r\n\t   | 2  |second nu" +
                        "mber |", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
 await testRunner.WhenAsync("I invoke the \"Auto Format Table\" command by typing \"|\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
 await testRunner.ThenAsync("the editor should be updated to", "Feature: Addition\r\nScenario: Add two numbers\r\n\tGiven the following numbers added\r" +
                        "\n\t\t| number | reason        |\r\n\t\t|      1 | first number  |\r\n\t\t|      2 | second" +
                        " number |", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Autoformats one-liner DataTable")]
        [Xunit.TraitAttribute("FeatureTitle", "Automatic table formatting command")]
        [Xunit.TraitAttribute("Description", "Autoformats one-liner DataTable")]
        public async System.Threading.Tasks.Task AutoformatsOne_LinerDataTable()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Autoformats one-liner DataTable", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 55
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 56
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 57
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n\tGiven the following numbers added\r" +
                        "\n\t\t|  number|    reason{caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
 await testRunner.WhenAsync("I invoke the \"Auto Format Table\" command by typing \"|\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
 await testRunner.ThenAsync("the editor should be updated to", "Feature: Addition\r\nScenario: Add two numbers\r\n\tGiven the following numbers added\r" +
                        "\n\t\t| number | reason |", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Autoformats Examples table")]
        [Xunit.TraitAttribute("FeatureTitle", "Automatic table formatting command")]
        [Xunit.TraitAttribute("Description", "Autoformats Examples table")]
        public async System.Threading.Tasks.Task AutoformatsExamplesTable()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Autoformats Examples table", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 73
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 74
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 75
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario Outline: Add two numbers\r\n\tWhen I press add\r\nExamples" +
                        ": \r\n\t|  number| reason |\r\n\t\t  |   1   {caret} first number  |\r\n\t   | 2  |second " +
                        "number |", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
 await testRunner.WhenAsync("I invoke the \"Auto Format Table\" command by typing \"|\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 86
 await testRunner.ThenAsync("the editor should be updated to", "Feature: Addition\r\nScenario Outline: Add two numbers\r\n\tWhen I press add\r\nExamples" +
                        ": \r\n\t| number | reason        |\r\n\t|      1 | first number  |\r\n\t|      2 | second" +
                        " number |", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await AutomaticTableFormattingCommandFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await AutomaticTableFormattingCommandFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
