// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Reqnroll.VisualStudio.Specs.Features.Editor.Commands
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AutoFormatDocumentCommandFeature : object, Xunit.IClassFixture<AutoFormatDocumentCommandFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AutoFormatDocumentCommand.feature"
#line hidden
        
        public AutoFormatDocumentCommandFeature(AutoFormatDocumentCommandFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Editor/Commands", "Auto format document command", @"Rules:

* Feature file can be formatted with useful defaults
* Auto format should not add or remove empty lines
	* Should not change descriptions, comments
* Selected text of a feature file can be formatted
* Formatting rules can be configured with editorconfig
* Caret should stay in the same line where it was", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Misformatted feature file is cleaned up")]
        [Xunit.TraitAttribute("FeatureTitle", "Auto format document command")]
        [Xunit.TraitAttribute("Description", "Misformatted feature file is cleaned up")]
        public async System.Threading.Tasks.Task MisformattedFeatureFileIsCleanedUp()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Misformatted feature file is cleaned up", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 16
 await testRunner.AndAsync("the following feature file in the editor", @"			@featureTag    @US1
 Feature: Addition
     Rule: Calculator functions

  Background:
Given I have entered 50 into the calculator

  @focus
  @WIP              @US1.1
  Scenario: Add two numbers
Given the following numbers added
		|  number| reason |
		  |   1   | first number  |
	   | 2  |second number |
And foo
	When   bar

	Scenario Outline: Add multiple
		 Given I have entered <number1> to the calculator
		    And I have entered <number2> to the calculator
			When I check the output
			```
			1+2
			  3

close
			```

	  @optimal
	Examples:
		| number1 | number2 |
		| 1 | 2|
	Examples: negative numbers
		| number1 | number2 |
		| -101 | -59              |", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
 await testRunner.WhenAsync("I invoke the \"Auto Format Document\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
 await testRunner.ThenAsync("the editor should be updated to", @"@featureTag @US1
Feature: Addition
Rule: Calculator functions

Background:
    Given I have entered 50 into the calculator

@focus
@WIP @US1.1
Scenario: Add two numbers
    Given the following numbers added
        | number | reason        |
        |      1 | first number  |
        |      2 | second number |
    And foo
    When bar

Scenario Outline: Add multiple
    Given I have entered <number1> to the calculator
    And I have entered <number2> to the calculator
    When I check the output
        ```
        1+2
          3
        
        close
        ```

@optimal
Examples:
    | number1 | number2 |
    |       1 |       2 |
Examples: negative numbers
    | number1 | number2 |
    |    -101 |     -59 |", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="The formatting rules are customized from configuration file")]
        [Xunit.TraitAttribute("FeatureTitle", "Auto format document command")]
        [Xunit.TraitAttribute("Description", "The formatting rules are customized from configuration file")]
        public async System.Threading.Tasks.Task TheFormattingRulesAreCustomizedFromConfigurationFile()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The formatting rules are customized from configuration file", "\tIn this scenario all rules are specified and all of them is the opposite as the " +
                    "default.\r\n\tThe related editorconfig settings can be seen in the JSON comments.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 112
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 115
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 116
 await testRunner.AndAsync("the reqnroll.json configuration file contains", @"{ 
	""ide"": {
		""editor"": {
			""gherkinFormat"": {
				""indentFeatureChildren"": true, // editorconfig: gherkin_indent_feature_children = true
				""indentRuleChildren"": true, // editorconfig: gherkin_indent_rule_children = true
				""indentSteps"": false, // editorconfig: gherkin_indent_steps = false
				""indentAndSteps"": true, // editorconfig: gherkin_indent_and_steps = true
				""indentDataTable"": false, // editorconfig: gherkin_indent_datatable = false
				""indentDocString"": false, // editorconfig: gherkin_indent_docstring = false
				""indentExamples"": true, // editorconfig: gherkin_indent_examples = true
				""indentExamplesTable"": false, // editorconfig: gherkin_indent_examples_table = false
				""tableCellPaddingSize"": 0, // editorconfig: gherkin_table_cell_padding_size = 0
				""tableCellRightAlignNumericContent"": false // editorconfig: gherkin_table_cell_right_align_numeric_content = false
			}
		}
	}
}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 137
 await testRunner.AndAsync("the following feature file in the editor", @"			@featureTag    @US1
 Feature: Addition
     Rule: Calculator functions

  Background:
Given I have entered 50 into the calculator

  @focus
  @WIP              @US1.1
  Scenario: Add two numbers
Given the following numbers added
		|  number| reason |
		  |   1   | first number  |
	   | 2  |second number |
And foo
	When   bar

	Scenario Outline: Add multiple
		 Given I have entered <number1> to the calculator
		    And I have entered <number2> to the calculator
			When I check the output
			```
			1+2
			  3

close
			```

	  @optimal
	Examples:
		| number1 | number2 |
		| 1 | 2|
	Examples: negative numbers
		| number1 | number2 |
		| -101 | -59              |", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 175
 await testRunner.WhenAsync("I invoke the \"Auto Format Document\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 176
 await testRunner.ThenAsync("the editor should be updated to", @"@featureTag @US1
Feature: Addition
    Rule: Calculator functions

        Background:
        Given I have entered 50 into the calculator

        @focus
        @WIP @US1.1
        Scenario: Add two numbers
        Given the following numbers added
        |number|reason       |
        |1     |first number |
        |2     |second number|
            And foo
        When bar

        Scenario Outline: Add multiple
        Given I have entered <number1> to the calculator
            And I have entered <number2> to the calculator
        When I check the output
        ```
        1+2
          3
        
        close
        ```

            @optimal
            Examples:
            |number1|number2|
            |1      |2      |
            Examples: negative numbers
            |number1|number2|
            |-101   |-59    |", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Caret is moved to the end of the line")]
        [Xunit.TraitAttribute("FeatureTitle", "Auto format document command")]
        [Xunit.TraitAttribute("Description", "Caret is moved to the end of the line")]
        public async System.Threading.Tasks.Task CaretIsMovedToTheEndOfTheLine()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Caret is moved to the end of the line", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 218
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 219
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 220
 await testRunner.AndAsync("the following feature file in the editor", "\tFeature: {caret}Addition\r\nScenario: Add two numbers", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 225
 await testRunner.WhenAsync("I invoke the \"Auto Format Document\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 226
 await testRunner.ThenAsync("the editor should be updated to", "Feature: Addition{caret}\r\nScenario: Add two numbers", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Selected part of feature file is formatted")]
        [Xunit.TraitAttribute("FeatureTitle", "Auto format document command")]
        [Xunit.TraitAttribute("Description", "Selected part of feature file is formatted")]
        public async System.Threading.Tasks.Task SelectedPartOfFeatureFileIsFormatted()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Selected part of feature file is formatted", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 234
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 235
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 236
 await testRunner.AndAsync("the following feature file in the editor", " Feature: Addition\r\n  Scenario: Add two numbers\r\nGiven t{sel}he following numbers" +
                        " added\r\n\t\t|  number| reason |\r\n\t\t  |   1   | first number  |\r\n\t   | 2  |second n" +
                        "umber |\r\nAnd {/sel}foo\r\n   When   bar", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 247
 await testRunner.WhenAsync("I invoke the \"Auto Format Selection\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 248
 await testRunner.ThenAsync("the editor should be updated to", " Feature: Addition\r\n  Scenario: Add two numbers\r\n    Given the following numbers " +
                        "added\r\n        | number | reason        |\r\n        |      1 | first number  |\r\n " +
                        "       |      2 | second number |\r\n    And foo\r\n   When   bar", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Caret line of feature file is formatted")]
        [Xunit.TraitAttribute("FeatureTitle", "Auto format document command")]
        [Xunit.TraitAttribute("Description", "Caret line of feature file is formatted")]
        public async System.Threading.Tasks.Task CaretLineOfFeatureFileIsFormatted()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Caret line of feature file is formatted", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 260
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 261
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 262
 await testRunner.AndAsync("the following feature file in the editor", " Feature: Addition\r\n  Scenario: Add two numbers\r\nGiven t{caret}he following numbe" +
                        "rs added\r\n   When   bar", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 269
 await testRunner.WhenAsync("I invoke the \"Auto Format Selection\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 270
 await testRunner.ThenAsync("the editor should be updated to", " Feature: Addition\r\n  Scenario: Add two numbers\r\n    Given the following numbers " +
                        "added\r\n   When   bar", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Formatting of Descriptions and Comments are not changed")]
        [Xunit.TraitAttribute("FeatureTitle", "Auto format document command")]
        [Xunit.TraitAttribute("Description", "Formatting of Descriptions and Comments are not changed")]
        public async System.Threading.Tasks.Task FormattingOfDescriptionsAndCommentsAreNotChanged()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Formatting of Descriptions and Comments are not changed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 280
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 282
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 283
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\n\tthis is an indented description\r\n\r\n#not working since 2000\r\nS" +
                        "cenario: Add two numbers\r\n  Todo: handle negative numbers\r\n\r\n    Given I have en" +
                        "tered 50 into the calculator", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 294
 await testRunner.WhenAsync("I invoke the \"Auto Format Document\" command without waiting for the tag changes", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 295
 await testRunner.ThenAsync("the editor should be updated to", "Feature: Addition\r\n\tthis is an indented description\r\n\r\n#not working since 2000\r\nS" +
                        "cenario: Add two numbers\r\n  Todo: handle negative numbers\r\n\r\n    Given I have en" +
                        "tered 50 into the calculator", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Repeating keywords are replaced with \"And\"")]
        [Xunit.TraitAttribute("FeatureTitle", "Auto format document command")]
        [Xunit.TraitAttribute("Description", "Repeating keywords are replaced with \"And\"")]
        public async System.Threading.Tasks.Task RepeatingKeywordsAreReplacedWithAnd()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Repeating keywords are replaced with \"And\"", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 309
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 311
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 312
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n    Given I have entered 50 into " +
                        "the calculator\r\n    Given I have entered 70 into the calculator\r\n\tWhen I add the" +
                        "m\r\n\tWhen I check the result\r\n\tThen there should be no error\r\n\tThen the result sh" +
                        "ould be 120", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 324
 await testRunner.WhenAsync("I invoke the \"Auto Format Document\" command without waiting for the tag changes", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 325
 await testRunner.ThenAsync("the editor should be updated to", @"Feature: Addition

Scenario: Add two numbers
    Given I have entered 50 into the calculator
    And I have entered 70 into the calculator
    When I add them
    And I check the result
    Then there should be no error
    And the result should be 120", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await AutoFormatDocumentCommandFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await AutoFormatDocumentCommandFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
