// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Reqnroll.VisualStudio.Specs.Features.Editor.Commands
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CommentAndUncommentCommandsFeature : object, Xunit.IClassFixture<CommentAndUncommentCommandsFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CommentUncommentCommand.feature"
#line hidden
        
        public CommentAndUncommentCommandsFeature(CommentAndUncommentCommandsFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Editor/Commands", "Comment and Uncomment commands", "Rules:\r\n\r\n* Comments out selected lines\r\n\t* Comments out caret line\r\n\t* Comments " +
                    "out selection lines with the smallest indent\r\n* Uncomments selected lines\r\n\t* Un" +
                    "comments selection lines\r\n\t* Uncomment ignores non-comment lines", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Comments out caret line")]
        [Xunit.TraitAttribute("FeatureTitle", "Comment and Uncomment commands")]
        [Xunit.TraitAttribute("Description", "Comments out caret line")]
        [Xunit.TraitAttribute("Category", "quarantine")]
        public async System.Threading.Tasks.Task CommentsOutCaretLine()
        {
            string[] tagsOfScenario = new string[] {
                    "quarantine"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Comments out caret line", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 15
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n\tWhen I press{caret} add", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
 await testRunner.WhenAsync("I invoke the \"Comment\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
 await testRunner.ThenAsync("the editor should be updated to", "Feature: Addition\r\nScenario: Add two numbers\r\n\t#When I press add", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Comments out selection lines with the smallest indent")]
        [Xunit.TraitAttribute("FeatureTitle", "Comment and Uncomment commands")]
        [Xunit.TraitAttribute("Description", "Comments out selection lines with the smallest indent")]
        public async System.Threading.Tasks.Task CommentsOutSelectionLinesWithTheSmallestIndent()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Comments out selection lines with the smallest indent", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 30
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\nScenario: Add two numbers\r\n\tWhen I press{sel} add\r\n\t\tAnd I pre" +
                        "ss multiply\r\n\t\t\tAnd I press{/sel} subtract", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
 await testRunner.WhenAsync("I invoke the \"Comment\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
 await testRunner.ThenAsync("the editor should be updated to", "Feature: Addition\r\nScenario: Add two numbers\r\n\t#When I press{caret} add\r\n\t#\tAnd I" +
                        " press multiply\r\n\t#\t\tAnd I press subtract", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Uncomments selection lines")]
        [Xunit.TraitAttribute("FeatureTitle", "Comment and Uncomment commands")]
        [Xunit.TraitAttribute("Description", "Uncomments selection lines")]
        public async System.Threading.Tasks.Task UncommentsSelectionLines()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Uncomments selection lines", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 49
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 50
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 51
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\n#Scenario: Add two numbers\r\n#\tWhen I press{sel} add\r\n#\t\tAnd I " +
                        "press {/sel}multiply\r\n#\t\t\tAnd I press subtract", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
 await testRunner.WhenAsync("I invoke the \"Uncomment\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
 await testRunner.ThenAsync("the editor should be updated to", "Feature: Addition\r\n#Scenario: Add two numbers\r\n\tWhen I press add\r\n\t\tAnd I press m" +
                        "ultiply\r\n#\t\t\tAnd I press subtract", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Uncomment ignores non-comment lines")]
        [Xunit.TraitAttribute("FeatureTitle", "Comment and Uncomment commands")]
        [Xunit.TraitAttribute("Description", "Uncomment ignores non-comment lines")]
        public async System.Threading.Tasks.Task UncommentIgnoresNon_CommentLines()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Uncomment ignores non-comment lines", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 69
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 70
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 71
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\n#Scenario: Add {sel}two numbers\r\n\tWhen I press add\r\n#\t\tAnd I p" +
                        "ress {/sel}multiply\r\n#\t\t\tAnd I press subtract", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
 await testRunner.WhenAsync("I invoke the \"Uncomment\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 80
 await testRunner.ThenAsync("the editor should be updated to", "Feature: Addition\r\nScenario: Add two numbers\r\n\tWhen I press add\r\n\t\tAnd I press mu" +
                        "ltiply\r\n#\t\t\tAnd I press subtract", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CommentAndUncommentCommandsFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CommentAndUncommentCommandsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
