// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Reqnroll.VisualStudio.Specs.Features.Editor.Commands
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class DefineStepsCommandFeature : object, Xunit.IClassFixture<DefineStepsCommandFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "DefineStepsCommand.feature"
#line hidden
        
        public DefineStepsCommandFeature(DefineStepsCommandFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Editor/Commands", "Define steps command", @"Rules:

* Lists all undefined steps
  * There are undefined steps
  * Two undefined step has the same step definition skeleton
* Shows error when all steps defined
  * All steps are defined
* Selected step definition skeletons can be copied to clipboard
  * Selected step definition skeletons are copied to clipboard
* Selected step definitions skeletons can be saved to a new file
  * Selected step definition skeletons are saved to a new file
  * Selected step definition skeletons are saved to a new file in StepDefinitions folder", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="There are undefined steps")]
        [Xunit.TraitAttribute("FeatureTitle", "Define steps command")]
        [Xunit.TraitAttribute("Description", "There are undefined steps")]
        public async System.Threading.Tasks.Task ThereAreUndefinedSteps()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("There are undefined steps", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "regex"});
                table1.AddRow(new string[] {
                            "Given",
                            "the operands have been entered"});
#line 18
 await testRunner.AndAsync("the following step definitions in the project:", ((string)(null)), table1, "And ");
#line hidden
#line 21
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tGiven the operands have been ent" +
                        "ered\r\n\tWhen I press multiply\r\n\tThen the result is calculated", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
 await testRunner.WhenAsync("I invoke the \"Define Steps\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "expression"});
                table2.AddRow(new string[] {
                            "When",
                            "I press multiply"});
                table2.AddRow(new string[] {
                            "Then",
                            "the result is calculated"});
#line 32
 await testRunner.ThenAsync("the define steps dialog should be opened with the following step definition skele" +
                        "tons", ((string)(null)), table2, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Two undefined step has the same step definition skeleton")]
        [Xunit.TraitAttribute("FeatureTitle", "Define steps command")]
        [Xunit.TraitAttribute("Description", "Two undefined step has the same step definition skeleton")]
        public async System.Threading.Tasks.Task TwoUndefinedStepHasTheSameStepDefinitionSkeleton()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Two undefined step has the same step definition skeleton", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 38
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 39
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tGiven the operand 4 has been ent" +
                        "ered\r\n\tAnd the operand 2 has been entered", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
 await testRunner.WhenAsync("I invoke the \"Define Steps\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "expression"});
                table3.AddRow(new string[] {
                            "Given",
                            "the operand {int} has been entered"});
#line 49
 await testRunner.ThenAsync("the define steps dialog should be opened with the following step definition skele" +
                        "tons", ((string)(null)), table3, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="All steps are defined")]
        [Xunit.TraitAttribute("FeatureTitle", "Define steps command")]
        [Xunit.TraitAttribute("Description", "All steps are defined")]
        public async System.Threading.Tasks.Task AllStepsAreDefined()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("All steps are defined", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 54
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "regex"});
                table4.AddRow(new string[] {
                            "Given",
                            "the operands have been entered"});
#line 55
 await testRunner.AndAsync("the following step definitions in the project:", ((string)(null)), table4, "And ");
#line hidden
#line 58
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tGiven the operands have been ent" +
                        "ered", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
 await testRunner.WhenAsync("I invoke the \"Define Steps\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
 await testRunner.ThenAsync("a ShowProblem dialog should be opened with \"All steps have been defined in this f" +
                        "ile already.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Selected step definition skeletons are copied to clipboard")]
        [Xunit.TraitAttribute("FeatureTitle", "Define steps command")]
        [Xunit.TraitAttribute("Description", "Selected step definition skeletons are copied to clipboard")]
        public async System.Threading.Tasks.Task SelectedStepDefinitionSkeletonsAreCopiedToClipboard()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Selected step definition skeletons are copied to clipboard", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 69
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 70
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 71
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tGiven the operands have been ent" +
                        "ered\r\n\tWhen I press multiply\r\n\tThen the result is calculated", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
 await testRunner.AndAsync("the \"Define Steps\" command is being invoked", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
 await testRunner.WhenAsync("I select the step definition snippets 0,1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 83
 await testRunner.AndAsync("close the define steps dialog with \"Copy to clipboard\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "expression"});
                table5.AddRow(new string[] {
                            "Given",
                            "the operands have been entered"});
                table5.AddRow(new string[] {
                            "When",
                            "I press multiply"});
#line 84
 await testRunner.ThenAsync("the following step definition snippets should be copied to the clipboard", ((string)(null)), table5, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Selected step definition skeletons are saved to a new file")]
        [Xunit.TraitAttribute("FeatureTitle", "Define steps command")]
        [Xunit.TraitAttribute("Description", "Selected step definition skeletons are saved to a new file")]
        public async System.Threading.Tasks.Task SelectedStepDefinitionSkeletonsAreSavedToANewFile()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Selected step definition skeletons are saved to a new file", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 89
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 90
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 91
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tGiven the operands have been ent" +
                        "ered\r\n\tWhen I press multiply\r\n\tThen the result is calculated", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 100
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 101
 await testRunner.AndAsync("the \"Define Steps\" command is being invoked", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 102
 await testRunner.WhenAsync("I select the step definition snippets 0,1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 103
 await testRunner.AndAsync("close the define steps dialog with \"Create\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "expression"});
                table6.AddRow(new string[] {
                            "Given",
                            "the operands have been entered"});
                table6.AddRow(new string[] {
                            "When",
                            "I press multiply"});
#line 104
 await testRunner.ThenAsync("the following step definition snippets should be in file \"AdditionStepDefinitions" +
                        ".cs\"", ((string)(null)), table6, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="DefineSteps command abides by reqnroll.json configuration for regex skeleton styl" +
            "e")]
        [Xunit.TraitAttribute("FeatureTitle", "Define steps command")]
        [Xunit.TraitAttribute("Description", "DefineSteps command abides by reqnroll.json configuration for regex skeleton styl" +
            "e")]
        public async System.Threading.Tasks.Task DefineStepsCommandAbidesByReqnroll_JsonConfigurationForRegexSkeletonStyle()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("DefineSteps command abides by reqnroll.json configuration for regex skeleton styl" +
                    "e", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 109
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 110
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 111
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Feature Using Regex Style\r\n\r\nScenario: Client has a simple basket\r\n\tGive" +
                        "n the client added 1 pcs to the basket", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 118
 await testRunner.AndAsync("the reqnroll.json configuration file contains", "{ \r\n\t\"trace\": { \"stepDefinitionSkeletonStyle\": \"RegexAttribute\" }\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
  await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
  await testRunner.WhenAsync("I invoke the \"Define Steps\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "expression"});
                table7.AddRow(new string[] {
                            "Given",
                            "the client added (.*) pcs to the basket"});
#line 126
  await testRunner.ThenAsync("the define steps dialog should be opened with the following step definition skele" +
                        "tons", ((string)(null)), table7, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="DefineSteps command properly escapes empty brackets when using Cucumber expressio" +
            "ns")]
        [Xunit.TraitAttribute("FeatureTitle", "Define steps command")]
        [Xunit.TraitAttribute("Description", "DefineSteps command properly escapes empty brackets when using Cucumber expressio" +
            "ns")]
        public async System.Threading.Tasks.Task DefineStepsCommandProperlyEscapesEmptyBracketsWhenUsingCucumberExpressions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("DefineSteps command properly escapes empty brackets when using Cucumber expressio" +
                    "ns", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 130
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 131
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 132
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Scenario using empty brackets\r\n\r\nScenario: Client has a simple basket\r\n\t" +
                        "When I use (parenthesis), {curly braces} and/or \\ backslash", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 139
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 140
 await testRunner.WhenAsync("I invoke the \"Define Steps\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "expression"});
                table8.AddRow(new string[] {
                            "When",
                            "I use \\(parenthesis), \\{curly braces} and\\/or \\\\ backslash"});
#line 141
 await testRunner.ThenAsync("the define steps dialog should be opened with the following step definition skele" +
                        "tons", ((string)(null)), table8, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="DefineSteps command properly escapes empty brackets when using Regex expressions")]
        [Xunit.TraitAttribute("FeatureTitle", "Define steps command")]
        [Xunit.TraitAttribute("Description", "DefineSteps command properly escapes empty brackets when using Regex expressions")]
        public async System.Threading.Tasks.Task DefineStepsCommandProperlyEscapesEmptyBracketsWhenUsingRegexExpressions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("DefineSteps command properly escapes empty brackets when using Regex expressions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 145
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 146
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 147
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Scenario using empty brackets\r\n\r\nScenario: Client has a simple basket\r\n\t" +
                        "When I use (parenthesis), {curly braces}, \\ backslash, and/or . period", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 154
 await testRunner.AndAsync("the reqnroll.json configuration file contains", "{ \r\n\t\"trace\": { \"stepDefinitionSkeletonStyle\": \"RegexAttribute\" }\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 160
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 161
 await testRunner.WhenAsync("I invoke the \"Define Steps\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "expression"});
                table9.AddRow(new string[] {
                            "When",
                            "I use \\(parenthesis\\), \\{curly braces}, \\\\ backslash, and/or \\. period"});
#line 162
 await testRunner.ThenAsync("the define steps dialog should be opened with the following step definition skele" +
                        "tons", ((string)(null)), table9, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="DefineSteps command abides by reqnroll.json configuration for async method declar" +
            "ation")]
        [Xunit.TraitAttribute("FeatureTitle", "Define steps command")]
        [Xunit.TraitAttribute("Description", "DefineSteps command abides by reqnroll.json configuration for async method declar" +
            "ation")]
        public async System.Threading.Tasks.Task DefineStepsCommandAbidesByReqnroll_JsonConfigurationForAsyncMethodDeclaration()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("DefineSteps command abides by reqnroll.json configuration for async method declar" +
                    "ation", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 166
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 167
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 168
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Feature Using Regex Style\r\n\r\nScenario: Client has a simple basket\r\n\tGive" +
                        "n the client has a basket", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 175
 await testRunner.AndAsync("the reqnroll.json configuration file contains", "{ \r\n\t\"trace\": { \"stepDefinitionSkeletonStyle\": \"AsyncRegexAttribute\" }\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 181
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 182
 await testRunner.WhenAsync("I invoke the \"Define Steps\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Method"});
                table10.AddRow(new string[] {
                            "MyProject.StepDefinitions1.GivenTheClientHasABasketAsync"});
#line 183
 await testRunner.ThenAsync("the define steps dialog should be opened with the following step definition skele" +
                        "tons", ((string)(null)), table10, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="DefineSteps command abides by reqnroll.json configuration for synchronous method " +
            "declaration")]
        [Xunit.TraitAttribute("FeatureTitle", "Define steps command")]
        [Xunit.TraitAttribute("Description", "DefineSteps command abides by reqnroll.json configuration for synchronous method " +
            "declaration")]
        public async System.Threading.Tasks.Task DefineStepsCommandAbidesByReqnroll_JsonConfigurationForSynchronousMethodDeclaration()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("DefineSteps command abides by reqnroll.json configuration for synchronous method " +
                    "declaration", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 187
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 188
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 189
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Feature Using Regex Style\r\n\r\nScenario: Client has a simple basket\r\n\tGive" +
                        "n the client has a basket", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 196
 await testRunner.AndAsync("the reqnroll.json configuration file contains", "{ \r\n\t\"trace\": { \"stepDefinitionSkeletonStyle\": \"RegexAttribute\" }\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 202
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 203
 await testRunner.WhenAsync("I invoke the \"Define Steps\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "Method"});
                table11.AddRow(new string[] {
                            "MyProject.StepDefinitions1.GivenTheClientHasABasket"});
#line 204
 await testRunner.ThenAsync("the define steps dialog should be opened with the following step definition skele" +
                        "tons", ((string)(null)), table11, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await DefineStepsCommandFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await DefineStepsCommandFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
