// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Reqnroll.VisualStudio.Specs.Features.Editor.Commands
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class FindUnusedStepDefinitionsCommandFeature : object, Xunit.IClassFixture<FindUnusedStepDefinitionsCommandFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "FindUnusedStepDefinitionCommand.feature"
#line hidden
        
        public FindUnusedStepDefinitionsCommandFeature(FindUnusedStepDefinitionsCommandFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Editor/Commands", "Find unused step definitions command", "List unused step definitions and allows jumping to the step definition method", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Find unused step definition with a single step definition attribute")]
        [Xunit.TraitAttribute("FeatureTitle", "Find unused step definitions command")]
        [Xunit.TraitAttribute("Description", "Find unused step definition with a single step definition attribute")]
        public async System.Threading.Tasks.Task FindUnusedStepDefinitionWithASingleStepDefinitionAttribute()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Find unused step definition with a single step definition attribute", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
 await testRunner.AndAsync("the following feature file \"Addition.feature\"", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I press add", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
 await testRunner.AndAsync("the following C# step definition class in the editor", "[Binding]\r\npublic class CalculatorSteps\r\n{\r\n\t[When(\"I press multiply\")]\r\n\tpublic " +
                        "void WhenIPressMultiply()\r\n\t{{caret} \r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
 await testRunner.WhenAsync("I invoke the \"Find Unused Step Definitions\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "step"});
                table15.AddRow(new string[] {
                            "Steps.cs(11,1): [When(\"I press multiply\")] MyProject.CalculatorSteps.WhenIPressMu" +
                                "ltiply"});
#line 29
 await testRunner.ThenAsync("a jump list \"Unused Step Definitions\" is opened with the following steps", ((string)(null)), table15, "Then ");
#line hidden
#line 32
 await testRunner.AndAsync("invoking the first item from the jump list navigates to the \"I press multiply\" \"W" +
                        "hen\" step definition", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Find unused step definition with a single step definition attribute across multip" +
            "le feature files")]
        [Xunit.TraitAttribute("FeatureTitle", "Find unused step definitions command")]
        [Xunit.TraitAttribute("Description", "Find unused step definition with a single step definition attribute across multip" +
            "le feature files")]
        public async System.Threading.Tasks.Task FindUnusedStepDefinitionWithASingleStepDefinitionAttributeAcrossMultipleFeatureFiles()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Find unused step definition with a single step definition attribute across multip" +
                    "le feature files", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
 await testRunner.AndAsync("the following feature file \"Addition.feature\"", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I press add", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
 await testRunner.AndAsync("the following feature file \"Subrtraction.feature\"", "Feature: Subtraction\r\n\r\nScenario: Sub two numbers\r\n\tWhen I press Sub", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
 await testRunner.AndAsync("the following C# step definition class in the editor", "[Binding]\r\npublic class CalculatorSteps\r\n{\r\n\t[When(\"I press multiply\")]\r\n\tpublic " +
                        "void WhenIPressMultiply()\r\n\t{{caret} \r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
 await testRunner.WhenAsync("I invoke the \"Find Unused Step Definitions\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "step"});
                table16.AddRow(new string[] {
                            "Steps.cs(11,1): [When(\"I press multiply\")] MyProject.CalculatorSteps.WhenIPressMu" +
                                "ltiply"});
#line 63
 await testRunner.ThenAsync("a jump list \"Unused Step Definitions\" is opened with the following steps", ((string)(null)), table16, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reports if there were no unused step definitions")]
        [Xunit.TraitAttribute("FeatureTitle", "Find unused step definitions command")]
        [Xunit.TraitAttribute("Description", "Reports if there were no unused step definitions")]
        public async System.Threading.Tasks.Task ReportsIfThereWereNoUnusedStepDefinitions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reports if there were no unused step definitions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 67
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 68
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 69
 await testRunner.AndAsync("the following feature file \"Addition.feature\"", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I press add", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
 await testRunner.AndAsync("the following C# step definition class in the editor", "[Binding]\r\npublic class CalculatorSteps\r\n{\r\n\t[When(\"I press add\")]\r\n\tpublic void " +
                        "WhenIPressAdd()\r\n\t{{caret} \r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 87
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 88
 await testRunner.WhenAsync("I invoke the \"Find Unused Step Definitions\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "step"});
                table17.AddRow(new string[] {
                            "There are no unused step definitions"});
#line 89
 await testRunner.ThenAsync("a jump list \"Unused Step Definitions\" is opened with the following steps", ((string)(null)), table17, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Only finds unused step definition attributes when the method had multiple attribu" +
            "tes")]
        [Xunit.TraitAttribute("FeatureTitle", "Find unused step definitions command")]
        [Xunit.TraitAttribute("Description", "Only finds unused step definition attributes when the method had multiple attribu" +
            "tes")]
        public async System.Threading.Tasks.Task OnlyFindsUnusedStepDefinitionAttributesWhenTheMethodHadMultipleAttributes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Only finds unused step definition attributes when the method had multiple attribu" +
                    "tes", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 95
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 96
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 97
 await testRunner.AndAsync("the following feature file \"Addition.feature\"", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I press add", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
 await testRunner.AndAsync("the following C# step definition class in the editor", "[Binding]\r\npublic class CalculatorSteps\r\n{\r\n\t[When(\"I press multiply\")]\r\n\t[Then(\"" +
                        "I press equals\")]\r\n\t[When(\"I press add\")]\r\n\tpublic void WhenIPressMultiply()\r\n\t{" +
                        "{caret} \r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 117
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 118
 await testRunner.WhenAsync("I invoke the \"Find Unused Step Definitions\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "step"});
                table18.AddRow(new string[] {
                            "Steps.cs(13,1): [When(\"I press multiply\")] MyProject.CalculatorSteps.WhenIPressMu" +
                                "ltiply"});
                table18.AddRow(new string[] {
                            "Steps.cs(13,1): [Then(\"I press equals\")] MyProject.CalculatorSteps.WhenIPressMult" +
                                "iply"});
#line 119
 await testRunner.ThenAsync("a jump list \"Unused Step Definitions\" is opened with the following steps", ((string)(null)), table18, "Then ");
#line hidden
#line 123
 await testRunner.AndAsync("invoking the first item from the jump list navigates to the \"I press multiply\" \"W" +
                        "hen\" step definition", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await FindUnusedStepDefinitionsCommandFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await FindUnusedStepDefinitionsCommandFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
