// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Reqnroll.VisualStudio.Specs.Features.Editor.Commands
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class FindStepDefinitionUsagesCommandFeature : object, Xunit.IClassFixture<FindStepDefinitionUsagesCommandFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "FindStepDefinitionUsagesCommand.feature"
#line hidden
        
        public FindStepDefinitionUsagesCommandFeature(FindStepDefinitionUsagesCommandFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Editor/Commands", "Find step definition usages command", @"Rules:
* List usages of a step definition and allows jumping to the usage
	* Finds usages of a step definition with a few usage
	* Finds usage of a step definition with a single usage
* Detects and report unused step definition
	* The step definition is not used
* Manual: Offers to show usages in the search window", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Finds usage of a step definition with a single usage")]
        [Xunit.TraitAttribute("FeatureTitle", "Find step definition usages command")]
        [Xunit.TraitAttribute("Description", "Finds usage of a step definition with a single usage")]
        public async System.Threading.Tasks.Task FindsUsageOfAStepDefinitionWithASingleUsage()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Finds usage of a step definition with a single usage", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
 await testRunner.AndAsync("the following feature file \"Addition.feature\"", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I press add", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
 await testRunner.AndAsync("the following C# step definition class in the editor", "[Binding]\r\npublic class CalculatorSteps\r\n{\r\n\t[When(\"I press add\")]\r\n\tpublic void " +
                        "WhenIPressAdd()\r\n\t{{caret} \r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
 await testRunner.WhenAsync("I invoke the \"Find Step Definition Usages\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "step"});
                table12.AddRow(new string[] {
                            "Addition.feature(4,2): When I press add"});
#line 33
 await testRunner.ThenAsync("a jump list \"Step definition usages\" is opened with the following steps", ((string)(null)), table12, "Then ");
#line hidden
#line 36
 await testRunner.AndAsync("invoking the first item from the jump list navigates to the \"I press add\" step in" +
                        " \"Addition.feature\" line 4", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Finds usage of a step definition with a few usage")]
        [Xunit.TraitAttribute("FeatureTitle", "Find step definition usages command")]
        [Xunit.TraitAttribute("Description", "Finds usage of a step definition with a few usage")]
        public async System.Threading.Tasks.Task FindsUsageOfAStepDefinitionWithAFewUsage()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Finds usage of a step definition with a few usage", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
 await testRunner.AndAsync("the following feature file \"Addition.feature\"", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I press add\r\n\tWhen I press " +
                        "add\r\nScenario: Other scenario\r\n\tWhen I press add", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
 await testRunner.AndAsync("the following C# step definition class in the editor", "[Binding]\r\npublic class CalculatorSteps\r\n{\r\n\t[When(\"I press add\")]\r\n\tpublic void " +
                        "WhenIPressAdd()\r\n\t{{caret} \r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
 await testRunner.WhenAsync("I invoke the \"Find Step Definition Usages\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "step"});
                table13.AddRow(new string[] {
                            "Addition.feature(4,2): When I press add"});
                table13.AddRow(new string[] {
                            "Addition.feature(5,2): When I press add"});
                table13.AddRow(new string[] {
                            "Addition.feature(7,2): When I press add"});
#line 63
 await testRunner.ThenAsync("a jump list \"Step definition usages\" is opened with the following steps", ((string)(null)), table13, "Then ");
#line hidden
#line 68
 await testRunner.AndAsync("invoking the first item from the jump list navigates to the \"I press add\" step in" +
                        " \"Addition.feature\" line 4", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="The step definition is not used")]
        [Xunit.TraitAttribute("FeatureTitle", "Find step definition usages command")]
        [Xunit.TraitAttribute("Description", "The step definition is not used")]
        public async System.Threading.Tasks.Task TheStepDefinitionIsNotUsed()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The step definition is not used", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 71
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
 await testRunner.AndAsync("the following feature file \"Addition.feature\"", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I press multiply", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
 await testRunner.AndAsync("the following C# step definition class in the editor", "[Binding]\r\npublic class CalculatorSteps\r\n{\r\n\t[When(\"I press add\")]\r\n\tpublic void " +
                        "WhenIPressAdd()\r\n\t{{caret} \r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
 await testRunner.WhenAsync("I invoke the \"Find Step Definition Usages\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "step"});
                table14.AddRow(new string[] {
                            "Could not find any usage"});
#line 92
 await testRunner.ThenAsync("a jump list \"Step definition usages\" is opened with the following steps", ((string)(null)), table14, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await FindStepDefinitionUsagesCommandFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await FindStepDefinitionUsagesCommandFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
