// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Reqnroll.VisualStudio.Specs.Features.Editor.Commands
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GoToDefinitionCommandFeature : object, Xunit.IClassFixture<GoToDefinitionCommandFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GoToDefinitionCommand.feature"
#line hidden
        
        public GoToDefinitionCommandFeature(GoToDefinitionCommandFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Editor/Commands", "Go to definition command", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Jumps to the step definition")]
        [Xunit.TraitAttribute("FeatureTitle", "Go to definition command")]
        [Xunit.TraitAttribute("Description", "Jumps to the step definition")]
        public async System.Threading.Tasks.Task JumpsToTheStepDefinition()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Jumps to the step definition", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await testRunner.GivenAsync("there is a Reqnroll project scope with calculator step definitions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I press{caret} add", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
 await testRunner.WhenAsync("I invoke the \"Go To Definition\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
 await testRunner.ThenAsync("the source file of the \"I press add\" \"When\" step definition is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 17
 await testRunner.AndAsync("the caret is positioned to the step definition method", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Lists step definitions if multiple step definitions matching")]
        [Xunit.TraitAttribute("FeatureTitle", "Go to definition command")]
        [Xunit.TraitAttribute("Description", "Lists step definitions if multiple step definitions matching")]
        public async System.Threading.Tasks.Task ListsStepDefinitionsIfMultipleStepDefinitionsMatching()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Lists step definitions if multiple step definitions matching", "\te.g. at scenario outline or at background", tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "regex"});
                table19.AddRow(new string[] {
                            "When",
                            "I press add"});
                table19.AddRow(new string[] {
                            "When",
                            "I press multiply"});
#line 22
 await testRunner.AndAsync("the following step definitions in the project:", ((string)(null)), table19, "And ");
#line hidden
#line 26
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\n\r\nScenario Outline: Add two numbers\r\n\tWhen I press <what>{care" +
                        "t}\r\nExamples: \r\n\t| what     |\r\n\t| add      |\r\n\t| multiply |", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
 await testRunner.WhenAsync("I invoke the \"Go To Definition\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "step definition"});
                table20.AddRow(new string[] {
                            "I press add"});
                table20.AddRow(new string[] {
                            "I press multiply"});
#line 39
 await testRunner.ThenAsync("a jump list \"Go to step definitions\" is opened with the following items", ((string)(null)), table20, "Then ");
#line hidden
#line 43
 await testRunner.AndAsync("invoking the first item from the jump list navigates to the \"I press add\" \"When\" " +
                        "step definition", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Lists hooks related to the scenario")]
        [Xunit.TraitAttribute("FeatureTitle", "Go to definition command")]
        [Xunit.TraitAttribute("Description", "Lists hooks related to the scenario")]
        public async System.Threading.Tasks.Task ListsHooksRelatedToTheScenario()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Lists hooks related to the scenario", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 48
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "method"});
                table21.AddRow(new string[] {
                            "BeforeScenario",
                            "ResetDatabase"});
                table21.AddRow(new string[] {
                            "AfterScenario",
                            "SaveLogs"});
#line 49
 await testRunner.AndAsync("the following hooks in the project:", ((string)(null)), table21, "And ");
#line hidden
#line 53
 await testRunner.WhenAsync("the following feature file is opened in the editor", "Feature: Addition\r\n\r\n@login\r\nScenario: Add two{caret} numbers\r\n\tWhen I press add", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
 await testRunner.WhenAsync("I invoke the \"Go To Definition\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "hook",
                            "hook type"});
                table22.AddRow(new string[] {
                            "ResetDatabase",
                            "BeforeScenario"});
                table22.AddRow(new string[] {
                            "SaveLogs",
                            "AfterScenario"});
#line 63
 await testRunner.ThenAsync("a jump list \"Go to hooks\" is opened with the following items", ((string)(null)), table22, "Then ");
#line hidden
#line 67
 await testRunner.AndAsync("invoking the first item from the jump list navigates to the \"ResetDatabase\" hook", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cursor stands in a scenario header line")]
        [Xunit.TraitAttribute("FeatureTitle", "Go to definition command")]
        [Xunit.TraitAttribute("Description", "Cursor stands in a scenario header line")]
        public async System.Threading.Tasks.Task CursorStandsInAScenarioHeaderLine()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cursor stands in a scenario header line", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 71
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 72
 await testRunner.GivenAsync("there is a Reqnroll project scope with calculator step definitions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 73
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\n\r\nScenario: Add two {caret}numbers\r\n\tWhen I press add", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
 await testRunner.WhenAsync("I invoke the \"Go To Definition\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 82
 await testRunner.ThenAsync("there should be no navigation actions performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Navigate from an undefined step")]
        [Xunit.TraitAttribute("FeatureTitle", "Go to definition command")]
        [Xunit.TraitAttribute("Description", "Navigate from an undefined step")]
        public async System.Threading.Tasks.Task NavigateFromAnUndefinedStep()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Navigate from an undefined step", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 86
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 87
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 88
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I press multiply{caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 95
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 96
 await testRunner.WhenAsync("I invoke the \"Go To Definition\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 97
 await testRunner.ThenAsync("the step definition skeleton for the \"I press multiply\" \"When\" step should be off" +
                        "ered to copy to clipboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GoToDefinitionCommandFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GoToDefinitionCommandFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
