// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Reqnroll.VisualStudio.Specs.Features.Editor.Commands
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GoToHooksCommandFeature : object, Xunit.IClassFixture<GoToHooksCommandFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GoToHooksCommand.feature"
#line hidden
        
        public GoToHooksCommandFeature(GoToHooksCommandFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Editor/Commands", "Go to hooks command", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Lists hooks executed for the scenario")]
        [Xunit.TraitAttribute("FeatureTitle", "Go to hooks command")]
        [Xunit.TraitAttribute("Description", "Lists hooks executed for the scenario")]
        public async System.Threading.Tasks.Task ListsHooksExecutedForTheScenario()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Lists hooks executed for the scenario", "\te.g. multiple [BeforeScenario], or [BeforeScenario] and [AfterScenario]", tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "type",
                            "method",
                            "tag scope",
                            "hook order"});
                table23.AddRow(new string[] {
                            "BeforeScenario",
                            "ResetDatabase",
                            "",
                            "1"});
                table23.AddRow(new string[] {
                            "BeforeScenario",
                            "LoginUser",
                            "@login",
                            "2"});
                table23.AddRow(new string[] {
                            "BeforeScenario",
                            "NotInScope",
                            "@otherTag",
                            ""});
                table23.AddRow(new string[] {
                            "AfterScenario",
                            "SaveLogs",
                            "",
                            ""});
                table23.AddRow(new string[] {
                            "BeforeTestRun",
                            "StartBrowser",
                            "",
                            ""});
                table23.AddRow(new string[] {
                            "BeforeFeature",
                            "ClearCache",
                            "",
                            "20"});
                table23.AddRow(new string[] {
                            "BeforeFeature",
                            "ClearBasicCache",
                            "@basic",
                            "10"});
                table23.AddRow(new string[] {
                            "BeforeFeature",
                            "ClearOtherCache",
                            "@otherFeatureTag",
                            ""});
                table23.AddRow(new string[] {
                            "AfterTestRun",
                            "StopBrowser",
                            "",
                            ""});
                table23.AddRow(new string[] {
                            "BeforeScenarioBlock",
                            "PrepareData",
                            "",
                            ""});
                table23.AddRow(new string[] {
                            "AfterStep",
                            "LogStep",
                            "",
                            ""});
#line 8
 await testRunner.AndAsync("the following hooks in the project:", ((string)(null)), table23, "And ");
#line hidden
#line 21
 await testRunner.WhenAsync("the following feature file is opened in the editor", "@basic\r\nFeature: Addition\r\n\r\n@login\r\nScenario: Add two numbers\r\n\tWhen I {caret}pr" +
                        "ess add", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
 await testRunner.WhenAsync("I invoke the \"Go To Hooks\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "hook",
                            "hook type",
                            "hook scope"});
                table24.AddRow(new string[] {
                            "StartBrowser",
                            "BeforeTestRun",
                            ""});
                table24.AddRow(new string[] {
                            "ClearBasicCache",
                            "BeforeFeature",
                            "@basic"});
                table24.AddRow(new string[] {
                            "ClearCache",
                            "BeforeFeature",
                            ""});
                table24.AddRow(new string[] {
                            "ResetDatabase",
                            "BeforeScenario",
                            ""});
                table24.AddRow(new string[] {
                            "LoginUser",
                            "BeforeScenario",
                            "@login"});
                table24.AddRow(new string[] {
                            "PrepareData",
                            "BeforeScenarioBlock",
                            ""});
                table24.AddRow(new string[] {
                            "LogStep",
                            "AfterStep",
                            ""});
                table24.AddRow(new string[] {
                            "SaveLogs",
                            "AfterScenario",
                            ""});
                table24.AddRow(new string[] {
                            "StopBrowser",
                            "AfterTestRun",
                            ""});
#line 32
 await testRunner.ThenAsync("a jump list \"Go to hooks\" is opened with the following items", ((string)(null)), table24, "Then ");
#line hidden
#line 43
 await testRunner.AndAsync("invoking the first item from the jump list navigates to the \"StartBrowser\" hook", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GoToHooksCommandFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GoToHooksCommandFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
