// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Reqnroll.VisualStudio.Specs.Features.Editor.Commands
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class RenameStepsCommandFeature : object, Xunit.IClassFixture<RenameStepsCommandFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "RenameStepsCommand.feature"
#line hidden
        
        public RenameStepsCommandFeature(RenameStepsCommandFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Editor/Commands", "RenameStepsCommand", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A simple step with a sigle usage is renamed from step definition (code side)")]
        [Xunit.TraitAttribute("FeatureTitle", "RenameStepsCommand")]
        [Xunit.TraitAttribute("Description", "A simple step with a sigle usage is renamed from step definition (code side)")]
        public async System.Threading.Tasks.Task ASimpleStepWithASigleUsageIsRenamedFromStepDefinitionCodeSide()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A simple step with a sigle usage is renamed from step definition (code side)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
 await testRunner.AndAsync("the following feature file \"Addition.feature\"", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I press add", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
 await testRunner.AndAsync("the following C# step definition class in the editor", "[Binding]\r\npublic class CalculatorSteps\r\n{\r\n\t[When(\"I press add\")]\r\n\tpublic void " +
                        "WhenIPressAdd()\r\n\t{{caret}\r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
 await testRunner.AndAsync("the \"Rename Step\" command is being invoked", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
 await testRunner.WhenAsync("I specify \"I choose add\" as renamed step", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
 await testRunner.ThenAsync("the file \"Addition.feature\" should be updated to", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I choose add", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 35
    await testRunner.AndAsync("the editor should be updated to contain", "[Binding]\r\npublic class CalculatorSteps\r\n{\r\n\t[When(\"I choose add\")]\r\n\tpublic void" +
                        " WhenIPressAdd()\r\n\t{\r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A step is renamed from feature file")]
        [Xunit.TraitAttribute("FeatureTitle", "RenameStepsCommand")]
        [Xunit.TraitAttribute("Description", "A step is renamed from feature file")]
        public async System.Threading.Tasks.Task AStepIsRenamedFromFeatureFile()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A step is renamed from feature file", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 49
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 50
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 51
 await testRunner.AndAsync("the following C# step definition class", "[Binding]\r\npublic class CalculatorSteps\r\n{\r\n\t[When(\"I press add\")]\r\n\tpublic void " +
                        "WhenIPressAdd()\r\n\t{\r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
 await testRunner.AndAsync("the following feature file in the editor", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I press add{caret}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
 await testRunner.AndAsync("the \"Rename Step\" command is being invoked", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
 await testRunner.WhenAsync("I specify \"I choose add\" as renamed step", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 72
 await testRunner.ThenAsync("the file \"Feature1.feature\" should be updated to", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I choose add", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 79
    await testRunner.AndAsync("the editor should be updated to contain", "[Binding]\r\npublic class CalculatorSteps\r\n{\r\n\t[When(\"I choose add\")]\r\n\tpublic void" +
                        " WhenIPressAdd()\r\n\t{\r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Multiple step definitions declared for the method")]
        [Xunit.TraitAttribute("FeatureTitle", "RenameStepsCommand")]
        [Xunit.TraitAttribute("Description", "Multiple step definitions declared for the method")]
        public async System.Threading.Tasks.Task MultipleStepDefinitionsDeclaredForTheMethod()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Multiple step definitions declared for the method", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 95
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 96
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 97
 await testRunner.AndAsync("the following feature file \"Addition.feature\"", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I press add", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
 await testRunner.AndAsync("the following C# step definition class in the editor", "[Binding]\r\npublic class CalculatorSteps\r\n{\r\n\t[Given(\"I press add\")]\r\n\t[When(\"I pr" +
                        "ess add\")]\r\n\t[When(\"I invoke add\")]\r\n\tpublic void WhenIPressAdd()\r\n\t{{caret} \r\n\t" +
                        "}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 117
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 118
 await testRunner.WhenAsync("I invoke the \"Rename Step\" command without waiting for the tag changes", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "step type",
                            "step definition"});
                table25.AddRow(new string[] {
                            "Given",
                            "I press add"});
                table25.AddRow(new string[] {
                            "When",
                            "I press add"});
                table25.AddRow(new string[] {
                            "When",
                            "I invoke add"});
#line 119
 await testRunner.ThenAsync("a jump list \"Choose step definition to rename\" is opened with the following items" +
                        "", ((string)(null)), table25, "Then ");
#line hidden
#line 124
 await testRunner.AndAsync("invoking the first item from the jump list renames the \"I press add\" \"Given\" step" +
                        " definition", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A parametrized step definition is renamed from code side")]
        [Xunit.TraitAttribute("FeatureTitle", "RenameStepsCommand")]
        [Xunit.TraitAttribute("Description", "A parametrized step definition is renamed from code side")]
        public async System.Threading.Tasks.Task AParametrizedStepDefinitionIsRenamedFromCodeSide()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A parametrized step definition is renamed from code side", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 133
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 134
 await testRunner.GivenAsync("there is a Reqnroll project scope", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 135
 await testRunner.AndAsync("the following feature file \"Addition.feature\"", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I add the numbers 5 and 3 t" +
                        "ogether", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 142
 await testRunner.AndAsync("the following C# step definition class in the editor", "[Binding]\r\npublic class CalculatorSteps\r\n{\r\n\t[When(@\"I add the numbers (.*) and (" +
                        "\\d+) together\")]\r\n\tpublic void WhenIAddTheNumbersTogether(int op1, int op2)\r\n\t{{" +
                        "caret} \r\n\t}\r\n}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 153
 await testRunner.AndAsync("the project is built and the initial binding discovery is performed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 154
 await testRunner.AndAsync("the \"Rename Step\" command is being invoked", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 155
 await testRunner.WhenAsync("I specify \"I sum the numbers (.*) and (\\d+) up\" as renamed step", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 156
 await testRunner.ThenAsync("the file \"Addition.feature\" should be updated to", "Feature: Addition\r\n\r\nScenario: Add two numbers\r\n\tWhen I sum the numbers 5 and 3 u" +
                        "p", ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 163
    await testRunner.AndAsync("the editor should be updated to contain", "[Binding]\r\npublic class CalculatorSteps\r\n{\r\n\t[When(@\"I sum the numbers (.*) and (" +
                        "\\d+) up\")]\r\n\tpublic void WhenIAddTheNumbersTogether(int op1, int op2)\r\n\t{ \r\n\t}\r\n" +
                        "}", ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await RenameStepsCommandFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await RenameStepsCommandFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
